### ISSUE TITLE
Schema: Add ability to drop indexes

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#10]
Need to be able to do `drop_primary`, `drop_unique` and `drop_index`

**Comment by corentinalcoy** [comment]
@josephmancuso  can I have this one?

**Comment by josephmancuso** [comment]
Yes. The API should look like this: https://orator-orm.com/docs/0.9/schema_builder.html#dropping-indexes

**Comment by corentinalcoy** [comment]
I think you should add `index`, `primary` functions before to complete this issue

**Comment by josephmancuso** [comment]
for adding constraints?

**Comment by corentinalcoy** [comment]
Yes

**Comment by josephmancuso** [comment]
Yes @marlysson is working on something here https://github.com/MasoniteFramework/orm/pull/46

**Comment by corentinalcoy** [comment]
I thought that he works just on foreign keys. 

I am talking about this https://orator-orm.com/docs/0.9/schema_builder.html#adding-indexes

**Comment by josephmancuso** [comment]
You are right. we have primary keys already but we may need to add normal indexes first https://github.com/MasoniteFramework/orm/blob/bb26afaa355ac6e62b219580f9ebe58e4a5209d4/tests/schema/mysql/test_mysql_schema.py#L265

**Comment by corentinalcoy** [comment]
> You are right. we have primary keys already but we may need to add normal indexes first
> 
> https://github.com/MasoniteFramework/orm/blob/bb26afaa355ac6e62b219580f9ebe58e4a5209d4/tests/schema/mysql/test_mysql_schema.py#L265

The simple MySQL request to a drop primary key is `alter table  table_name drop primary key`
I don't get why we need to pass an argument to `drop_primary`

**Comment by corentinalcoy** [comment]
I can add index methods

**Comment by josephmancuso** [comment]
@corentinalcoy Ok awesome you can work on this issue https://github.com/MasoniteFramework/orm/issues/76

**Comment by corentinalcoy** [comment]
> > You are right. we have primary keys already but we may need to add normal indexes first
> > https://github.com/MasoniteFramework/orm/blob/bb26afaa355ac6e62b219580f9ebe58e4a5209d4/tests/schema/mysql/test_mysql_schema.py#L265
> 
> The simple MySQL request to drop primary key is `alter table table_name drop primary key`
> I don't get why we need to pass an argument to `drop_primary`

@josephmancuso  And this?

**Comment by josephmancuso** [comment]
hmm not sure. You can have multiple columns as a primary key though. For now I guess just build no parameters going to it and later we can add support for things like composite keys

**Comment by Marlysson** [comment]
@josephmancuso On #46 I'll add constraints and drop index of type foreign key.

With #76 created ( talking about unique index ), how to handle the unique constraint already created? Who does this, he will make git pull before?

**Comment by josephmancuso** [comment]
All these things can really happen at the same time. We just need to make sure the format is correct

**Comment by Marlysson** [comment]
@corentinalcoy If you aren't working in this... @josephmancuso can you assign me to this?

**Comment by josephmancuso** [comment]
@Marlysson I'm not sure. @corentinalcoy will have to comment. If hes not working on it i'll assign it to you

**Comment by ghost** [comment]
I am testing... 
It will be done in a few hours

**Comment by ghost** [comment]
@josephmancuso 
I found some 'errors' in the project. 
I will show when I will turn on my computer..
