### ISSUE TITLE
Cannot Serialize a relationships relationship

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#107]
I have been trying for 2 full days to find a way to get this to work and I just cannot figure it out.

if we have something like this:

```python
user = User.with_('articles').get()
user.serialize()
```

This produces the correct dictionary. Something like this:

```python
{
    "id": 1,
    "name": "Joe",
    "articles": [{
        "id": 1,
        ...
    },{
        "id": 2,
        ...
    },
]
}
```

But i cannot get something like
```
```python
user = User.with_('articles', 'articles.logo').get()
user.serialize()
```

to work properly

**Comment by Marlysson** [comment]
@josephmancuso Which error appears when test is ran.. or just the dict isn't in the correct structure?

**Comment by josephmancuso** [comment]
@Marlysson i've rewritten this so many times i'm not even sure anymore lol. But I was getting recursion issues because the model was seraizling, which was serializing the collection of models, which was serializing the model, which was serializing the collection etc etc.

I might need to revert a bunch of commits cuss now i'm not sure if even the format is good anymore.

Originally this was only happening if a relationship was pointing back to the model like:

```python
User.with_('articles.user').get() <-- points back to user model
```

but i probably screwed that all up now

**Comment by josephmancuso** [comment]
I actually figured this out
