### ISSUE TITLE
Schema: Add foreign key constraints

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#11]
should be in a format like 

```
table.foreign('user_id').references('id').on('users')
```

**Comment by josephmancuso** [comment]
as well as `on_delete` and `on_update`

**Comment by josephmancuso** [comment]
@Marlysson, since you are familiar with the schema builder, do you want to take a crack at this one?

**Comment by Marlysson** [comment]
Sure, I can try to complete this. Any questions I will put here.

**Comment by Marlysson** [comment]
@josephmancuso 

Analysing this line:

```table.foreign('user_id').references('id').on('users')```

Firstly should have one line defining which column will be used for the foreign key like this:

```table.integer('user_id')```, right?

Is necessary the use of ```.unsigned()``` method to create it?

> Because Orator and Laravel do the same ( using _unsigned_ ). And if it wasn't used, cause some exception.. as said here:
[Laravel exception when running migrations](https://laraveldaily.com/foreign-keys-with-migrations-dont-forget-unsigned/) ( just for example )

**Comment by josephmancuso** [comment]
> Firstly should have one line defining which column will be used for the foreign key like this:

yes. you are creating a constraint. So an constraint needs to be applied to a column that exists already.

> Is necessary the use of .unsigned() method to create it?

Technically no but the the column you are defining needs to be the same data type apples to apples as the foreign column.

For example if you are making a foreign key from `table1.id` to `table2.column_id`, `column_id` and `id` columns must both be the same data type for the database to accept the foreign key constraint. If one is unsigned then the other has to be unsigned

**Comment by josephmancuso** [comment]
technically it should be unsigned by default since you're never going to have a negative number in these columns

**Comment by josephmancuso** [comment]
For others following, with numbers you technically use the first bit to check if the number is negative or positive. When you make it unsigned you tell the database to use the left bit to make the number bigger. In this case you lose the ability to make the column have a negative value but you gain the ability to make the number larger (since now you have an extra bit to work with)

**Comment by josephmancuso** [comment]
primary keys and foreign keys are never negative so it makes sense to make the columns unsigned.
