### ISSUE TITLE
Change acessor attribute naming convention

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#121]
Right now we have the naming convention as `get_{attribute_name}`. I think this should be `get_{attribute_name}_attribute`.

This is coming from a similar Laravel convention

**Comment by josephmancuso** [comment]
This is a pretty simple change. The change should be made in the `__getattr__` method of the `Model` class.

**Comment by corentinalcoy** [comment]
@josephmancuso assign me this one

**Comment by josephmancuso** [comment]
All yours
