### ISSUE TITLE
Be compatible to use UUID as primary key

### ISSUE THREAD

**Issue by rfschubert** [MasoniteFramework/orm#122]
As per default in many databases, we should be able to use `uuid` as `pk`.

On `postgres` databases it is common to use `uuid` and not `int` as default `pk`. But is not forced users to use `uuid` so it may be easy to set which type of field we want to use.

`Django` currently forces user to declare the desired `id` and overrides the default, but need be done in every table, and it is quite annoying.

```python
from django.db import models

class MyTable(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)


class MyAnotherTable(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)


class MyAnotherTableAgain(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
```

An idea is to use global config variable, as one way to override, but user still may be able to declare by itself.

*Sample:*
```python
OVERRIDE_DEFAULT_ID_FIELD_TYPE = "uuid"
```

I know use cases where system have almost all tables using `uuid` field as default and only 1 table with `int` as `pk` because of specific law pattern of one data that must be stored, so others users will also want to have `auto increment` on few tables.

**Comment by josephmancuso** [comment]
oh i like this

**Comment by josephmancuso** [comment]
so you're saying when you do 

```
table.increments('something')
```

it actually can map to a UUID?

**Comment by rfschubert** [comment]
I don't see currently do `table.increments('something')` as useful, but for sample:

I'm using an table to generate sequential numbers because I need to use it on a gov database document.

So I have only one table on my mainframe like this:

```python
class MyIntegerTable(models.Model):
    pass
```
Because for default `Django` will use `id` as auto increment.

And also I have others `85~90` tables using `uuid` as primary key... so I have dozens of lines repeatedly on my projects with
```
id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
```

But I think it was more simple to tell the ORM that I want to use for default `uuid` and only use `int` as id if I need. So I would have almost all servers without the need to manually specify that `pk` should be `uuid` in every table, and only one line telling to my ORM that my `MyIntegerTable` should have `int` as `pk`.

**Comment by rfschubert** [comment]
I think that if I create a new table, It can generate the `id` field by itself, as every table should have an `id` field as `pk`.

But we should be able to configure ORM like we do with other things (host, username) that it must map `id` fields as `uuid` for default. It would clean lots of lines of code from models.

**Comment by hamzzy** [comment]
any guide on i would love to contribute to this

**Comment by josephmancuso** [comment]
@hamzzy this will be hold until #181 in merged in

**Comment by hamzzy** [comment]
okay @josephmancuso
