### ISSUE TITLE
Collection pluck should return a collection, not the plucked results

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#131]

**Comment by Marlysson** [comment]
@josephmancuso Is this issue solved?
I've verify the pluck method and it return ```Collection(attributes)```, Should be done something more?

**Comment by josephmancuso** [comment]
No I did this. I was trying to replace orator in a masonite 3.0 branch so was making a bunch of bugs I found a long the way. I did this in a commit and pushed up
