### ISSUE TITLE
Implements a decorator using a context to handle operations inside a transaction.

### ISSUE THREAD

**Issue by Marlysson** [MasoniteFramework/orm#140]
Create a decorator like ```@transaction``` to handle operation that should ran into a transaction.

Example:
```python
@transaction
def create_charge(self,**kwargs):
    # Doing some stuff
```

Behind the scenes the connection class should run:

```python
connection.begin()
connection.query()
connection.commit()
connection.rollback()
```

In just one step or rollback all case something gets wrong.

**Comment by josephmancuso** [comment]
@Marlysson where should this go? is this in the model? a random method? Are we doing something like this?

```python

@transaction(connection='staging')
def charge(self):
    #..
```

or is this only going on the model and just pulls the connection from the model?

**Comment by Marlysson** [comment]
Se are almost doing this in connections class. I think lack transform in a context manager to join all operation in a single one. 

We have the begin_transaction, commit and rollback in connection resolver and in connections class. We could choice, to create from It and use `with db.transaction(...)` or a decorador in util.py file ( `@transaction(...)` ) , using a connection to method operation ( in controller by example )

**Comment by girardinsamuel** [comment]
In Django we can call this decorator on "any python functions", I guess it would be more flexible not to put it only on the model, if possible 👍 
Those are often put in a `decorators.py` module, so maybe in `connections/decorators.py` ? 

Makes sense to have this import:
```python
from masoniteorm.connections.decorators import transaction

@transaction(connection='staging')
def charge(self):
    #..
```

**Comment by josephmancuso** [comment]
I like that

**Comment by girardinsamuel** [comment]
@Marlysson @josephmancuso I can finish it if not started, I guess most of it is already done with latest additions

**Comment by josephmancuso** [comment]
Sure. This is really wrapper around what we already have so should be simple 👍

**Comment by josephmancuso** [comment]
Closing this for now. Can reopen if new requirements or needs come up https://github.com/MasoniteFramework/orm/pull/229
