### ISSUE TITLE
Eager load attribute on model

### ISSUE THREAD

**Issue by tpow** [MasoniteFramework/orm#142]
I think there are some cases where I always want to eager load a dependent model. I think this currently requires the with('other') construct or a join. Is it possible to add something to the model to indicate that any time I load it I always want to eager load the other so I don't have to remember to do it everywhere I build a query? I suppose this could be expressed as a variation on "belongs_to" or an additional decorator.

Admittedly this could be a sign of a badly designed model or poor database schema...

**Comment by josephmancuso** [comment]
no i think this is a great idea.

**Comment by josephmancuso** [comment]
Would you like to take a crack at it?

**Comment by tpow** [comment]
@josephmancuso Thanks, but having not even peeked at the new ORM code yet (I'm using Orator), I wouldn't know where to begin and don't currently have the time to dig into it.

**Comment by josephmancuso** [comment]
Added this in latest PR #162 

Done via adding a `__with__` to the model like it is now with Orator:

```python
class User:
    __with__ = ["profile", "articles"]
```
