### ISSUE TITLE
table.timestamps() should be nullable

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#146]
right now they are not nullable

see:

![Screen Shot 2020-07-25 at 11 31 19 AM](https://user-images.githubusercontent.com/20172538/88460466-6ab01000-ce6a-11ea-8f8a-7c2119956438.png)

**Comment by Marlysson** [comment]
for the `created_at` field semantically should be not nullable, don't?

**Comment by josephmancuso** [comment]
@Marlysson I'm not sure .. other frameworks seem to make them nullable

**Comment by josephmancuso** [comment]
I think its just annoying when creating records manually in the database. Needing to supply a created at and an updated at manually

**Comment by Marlysson** [comment]
@josephmancuso Yeah, I think annoying do this too. Does maybe the solution was a scope to that?

**Comment by josephmancuso** [comment]
fixed
