### ISSUE TITLE
Relationships can not be called.

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#151]
One of the points of a relationship is changing to a builder on the fly.

So for example this should work:

```python
x = User.all().first()
x.posts #== collection
x.posts() #== builder
x.posts().where('post_id', 1).first() #== the points of calling the relationship
```

For some reason this works in the tests but not when you actually try this

**Comment by josephmancuso** [comment]
I spent all weekend trying to figure this out and can't get it. going to give up for now. Maybe there will be a different way to do this

**Comment by josephmancuso** [comment]
Python doesn't like this approach even with hijacking all the magic methods

**Comment by josephmancuso** [comment]
we'll have to think of another way to do this

**Comment by josephmancuso** [comment]
Since python methods and attributes are basically all treated the same it's impossible to know if a relationship is being accessed `user.posts` or called `user.posts()` and because of that its impossible to hijack any magic methods and know what the user is doing.

**Comment by josephmancuso** [comment]
going to take another stab at this @girardinsamuel

**Comment by josephmancuso** [comment]
nope. Tried for a few hours and no idea how to implement this with what we have

**Comment by Marlysson** [comment]
>Since python methods and attributes are basically all treated the same it's impossible to know if a relationship is being accessed user.posts or called user.posts() and because of that its impossible to hijack any magic methods and know what the user is doing.

Thinking here about that.. When calling **user.posts()** if we check whether attribute is in Model and it's callable? So we'll discover that it's a method call that is being done.

Then call it as you made here ( Model ):
```python
def method(*args, **kwargs):
     return getattr(self.builder, attribute)(*args, **kwargs)
```

**Comment by josephmancuso** [comment]
@Marlysson easier said than done because Python treats attributes the same

**Comment by josephmancuso** [comment]
if you want to take a stab at this then please. I've spent many hours trying to figure this out lol. Orator did it but by looking at the code I couldn't really figure out how they did it

**Comment by josephmancuso** [comment]
It's deff possible somehow

**Comment by Marlysson** [comment]
Yeah, I was looking for in Orator code for some insight too, I'll looking more deep.
The right behavior is what you did in first comment ( Each type of call returning a different type of object  ) ?

**Comment by girardinsamuel** [comment]
I'll take a look at it too !

**Comment by Marlysson** [comment]
Maybe it's here that him does all:
https://github.com/sdispater/orator/blob/0.9/orator/orm/relations/wrapper.py

Now it's understand all that magic.

**Comment by josephmancuso** [comment]
looks like it. I actually haven't looked at that class at all
