### ISSUE TITLE
Think of ORM name

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#163]
Literally none of these names have any priorities. These are just random names I've thrown at the wall:

Contrive
Future
Envision 
precord 
Ever orm
Iron ORM
stratiform
FirestORM
stORM

**Comment by vaibhavmule** [comment]
Contrive is best! It stands out from all of them

**Comment by psyonara** [comment]
One meaning of contrive is to plan with evil intent. 😕

**Comment by psyonara** [comment]
How about keeping with the naming theme of Masonite?
Ideas:
* Cherry ORM
* Melamine ORM
* Mahogany ORM
* etc

My favorite is Cherry ORM. Since I like cherries and cherry wood. 😜 But Melamine ORM also works well.

**Comment by Marlysson** [comment]
**masorm** ( Masonite + ORM ) But without any other meaning.

**Comment by josephmancuso** [comment]
Canvas

**Comment by girardinsamuel** [comment]
@josephmancuso to help, could you give some background behind naming this framework "Masonite" ?

Thanks 👍  !!

**Comment by josephmancuso** [comment]
@girardinsamuel 

Masonite is a type of hardboard, a kind of engineered wood, which is made of steam-cooked and pressure-molded wood fibers in a process patented by William H. Mason. It is also called Quartrboard, Isorel, hernit, karlit, torex, treetex, and pressboard.

Masonite is a cork board type material that artists typically use to put their artwork on. I think I software development as a form of art so I thought building this art (software) and then putting it on a cork board type material to show the world (Masonite).

**Comment by girardinsamuel** [comment]
Oh okay thank you, I know this material then ! In French, we are calling it "Medium" (actually it gathers "Isorel" and MDF).
Medium ORM ? :) 

I like Canvas as it's in the maker/artist philosophy !

**Comment by josephmancuso** [comment]
Maker ORM?

**Comment by girardinsamuel** [comment]
> Maker ORM?

Makes sense both for framework philosophy and for the goal of an ORM ("making" model from/relating to database tables)

**Comment by josephmancuso** [comment]
So far I think the top choices are: 

Maker ORM (or just Maker)
Masonite ORM
Contrive

Something we have to remember is that whatever name we go with, a developer will have to type it every time they import something. 

So something like `maker` is easier to type than a suggestion like `melamine` or even `mahogany`. Something to always keep in mind of as package maintainers is you are likely building for someone who doesn't natively speak English.

**Comment by abarreraaponte** [comment]
CraftORM
Carpenter or CarpenterORM
HeraldORM
BeamORM
BoardORM

**Comment by josephmancuso** [comment]
For now, unless something else happens, the ORM will be called Masonite ORM
