### ISSUE TITLE
Error running masonite-orm command

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/orm#166]
After installing latest `masonite-orm` version in a new crafted Masonite 2.3.18 project and making require changes  (for migration) in `config/database.py` file and in `User.py` file, I ran into an issue when running `masonite-orm` command.

```
Traceback (most recent call last):
  File "/Users/samuel/.virtualenvs/masonite_test/bin/masonite-orm", line 5, in <module>
    from masonite.orm.commands.Entry import application
  File "/Users/samuel/.virtualenvs/masonite_test/lib/python3.8/site-packages/masonite/orm/commands/Entry.py", line 18, in <module>
    from wsgi import container
ModuleNotFoundError: No module named 'wsgi'
```
- There is a`wsgi.py` file is in my project root directory
- I have seen that the wsgi in the orm repo is not the same as we had before  ?!

**Comment by josephmancuso** [comment]
Fixed in the new 0.6 branch. This branch will be polished

**Comment by girardinsamuel** [comment]
Okay thank you very much. I did not find out how to dot, I've read what you've done 👍 .
I'll we able to continue working on the Inertia demo with Masonite ORM !

**Comment by josephmancuso** [comment]
I started fixing some things I've seen wrong after the refactoring last night with the schemas. I'll be rewriting that too and will release 0.6.1 which should be the most polished release yet so stay tuned for that :)
