### ISSUE TITLE
Fix fetching config from ORM

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/orm#173]
@josephmancuso how do you plan to fetch `database` config ?
Right now it is : 
```python
from config.database import DATABASES
```
Should we replace it by something like:
```python
from masonite.helpers import config
DATABASES = config("database.databases")
```

I got some issue with latest version when running masonite-orm command:
```bash
  ModuleNotFoundError
  No module named 'config'
  at ~/.virtualenvs/masonite_pingcrm/lib/python3.8/site-packages/masoniteorm/connections/ConnectionFactory.py:48 in make
      44│ 
      45│         Returns:
      46│             masonite.orm.connection.BaseConnection -- Returns an instance of a BaseConnection class.
      47│         """
    → 48│         from config.database import DATABASES
      49│ 
      50│         if key == "default":
      51│             connection_details = DATABASES.get(DATABASES.get("default"))
      52│             connection = self._connections.get(connection_details.get("driver"))
```

I know a lot of a refactoring is in progress and I don't if the "masonite config integration" has not been done yet or if it's a bug. Thanks 👍

**Comment by josephmancuso** [comment]
This is actually a great question and I'm not sure. I've been kicking the can down the road but somehow we need to make the configuration location adjustable. Orator does this by passing in the config location in the command. They also set a Db resolver class and pass in the setting which we can import that to get the connection settings (as it will then be an attribute on the class)

**Comment by girardinsamuel** [comment]
> we need to make the configuration location adjustable

Yes especially if the ORM can be used with or without Masonite.

I guess the big picture is:
* with Masonite come a DatabaseServiceProvider which could instantiate the ORM with the config as argument (coming from config/database.py).
* without it, we just instantiate the ORM with the config as argument which can come from anywhere.

**Comment by josephmancuso** [comment]
right exactly. People will complain if we force them to have files they don't want (like config/database.py).

One way is to make a new class like a `DatabaseResolver` class I think is what Orator uses.

Not sure if you know this but anytime you set an attribute on a class it will always be set on that class.

So if we made a class like this:

```
# package class file
class DatabaseResolver:

    _connection_settings = None

    @classmethod
    def set_connection_settings(cls, dictionary):
        cls._connection_settings = dictionary
```

then in the users project they need to put this code somewhere before the connections start happening:

```
# config/database.py but anywhere really:
from masoniteorm.resolver import DatabaseResolver

DATABASES = {
    'default': 'sqlite',
    'sqlite': ...
}

DatabaseResolver.set_connection_settings(DATABASES)
```

When we actually import this class somewhere inside our package it will now actually have the connection settings attached to it.

```
# Mysql Connection class
from masoniteorm.resolvers import DatabaseResolver

connection_details = DatabaseResolver. _connection_settings
#==  {
    'default': 'sqlite',
    'sqlite': ...
}
```

Since it was already imported first and had attributes attached to it.

This would be one approach we can take. Then anytime we need connection details we import the class instead of importing them from whatever file.

**Comment by josephmancuso** [comment]
for the masonite-orm command we may still need the directory and file because we need to call the module so it loads our resolver

**Comment by josephmancuso** [comment]
but that can be passed as an argument pretty easily

**Comment by girardinsamuel** [comment]
@josephmancuso I guess #174 fixed partially the issue, what is left is to create a DatabaseServiceProvider for Masonite.
Maybe I can try to do it as a first issue (as it's more Masonite "side" I might be more comfortable) ?

**Comment by josephmancuso** [comment]
```python
"""A ORMProvider Service Provider."""

from masonite.provider import ServiceProvider
from masoniteorm.commands import MakeMigrationCommand, MakeSeedCommand, MigrateCommand, MigrateRefreshCommand, MigrateRollbackCommand


class ORMProvider(ServiceProvider):
    """Provides Services To The Service Container."""

    wsgi = False

    def register(self):
        """Register objects into the Service Container."""
        self.commands(
            MakeMigrationCommand(),
            MakeSeedCommand(),
            MigrateCommand(),
            MigrateRefreshCommand(),
            MigrateRollbackCommand(),
        )

    def boot(self):
        """Boots services required by the container."""
        pass

```

This is what I have so far in one of my projects. This should exist in the package somewhere

**Comment by josephmancuso** [comment]
inside that service provider, like in the register method is where we can import the database config and add it to the connection resolver class

**Comment by josephmancuso** [comment]
we may have to lazy load masonite so it doesn't conflict with people who don't have Masonite installed

**Comment by girardinsamuel** [comment]
I will do that in a PR
