### ISSUE TITLE
Add support to able using soft deletes on blueprint table.

### ISSUE THREAD

**Issue by Marlysson** [MasoniteFramework/orm#178]
Add some method that on table creating be able to support soft deletes with `deleted_at` column.

Something like this:
```
table.soft_deletes()
```

References:

- Orator: https://orator-orm.com/docs/0.9/orm.html#soft-deleting
- Eloquent: https://laravel.com/docs/8.x/eloquent#soft-deleting

**Comment by Marlysson** [comment]
Solved by #181

**Comment by Marlysson** [comment]
@josephmancuso close this or more tests needed?

**Comment by josephmancuso** [comment]
Yup this is good
