### ISSUE TITLE
Add the ability to show the sql generated by a migration  

### ISSUE THREAD

**Issue by corentinalcoy** [MasoniteFramework/orm#180]
It should be good to add a command which helps to show the SQL generated by a migration.
This feature is something special for Django. I like Laravel but I don't see anything like this when I need to show the SQL of a migration.

Example:
```bash
masonite-orm sqlmigration migration_for_users_table
``` 
Output:
```SQL
BEGIN;
CREATE TABLE users (
    id serial NOT NULL PRIMARY KEY,
   name varchar(150) NOT NULL
);
COMMIT;
```
You can check for Django using the link below
https://docs.djangoproject.com/en/3.1/ref/django-admin/#django-admin-sqlmigrate

**Comment by josephmancuso** [comment]
@corentinalcoy I love it I think its a great idea and it also fits really well in the structure we have now. Will implement when we get there

**Comment by josephmancuso** [comment]
@Marlysson do you need any help on this one?

**Comment by Marlysson** [comment]
@josephmancuso I'm looking for how get the content inside .up() method to get the self.schema.blueprint.to_sql(), but until now I don't see how do this.

If uses the locate to instantiate the give migration, I need call .up() method to fill self.schema, but the migration is ran, and this is not behavior desired.

It's like "run context manager but don't run migration"

**Comment by josephmancuso** [comment]
We do this in the tests. We pass the dry parameter to the schema builder.

**Comment by josephmancuso** [comment]
You should be able to pass the dry parameter and then inside the schema class see if dry is set and then just print to_sql()

**Comment by Marlysson** [comment]
Ohh I see, I'll try here.

Is this docstring right?

https://github.com/MasoniteFramework/orm/blob/b9c5ab39c0f87f7e19a7247c58ea5b14233991a0/src/masoniteorm/schema/Schema.py#L54

**Comment by josephmancuso** [comment]
No. A lot of these docstrings are not up to date. I wasn't updating them when I did the rewrite

**Comment by Marlysson** [comment]
I don't know if I'm missing some step but besides create the command and add it to Entry.py is some additional step to add a new command and be available to test ( python orm migrate:sql ... ) ?

**Comment by josephmancuso** [comment]
Depends on how you are running the commands. You can also add it to the orm.py file and run it as "python orm your:command"
