### ISSUE TITLE
where  to record the query sql to file

### ISSUE THREAD

**Issue by li-linfeng** [MasoniteFramework/orm#188]
I'm a  Laravel user, and it's very happy to find masonite.

Now I  have  set the  log_queries: True,  and  i can see the sql in the craft serve window .
 I want to put sql into files  globally .

 I want to know  if there is an event like laravel  event ----QueryExecuted. 
This event is a global event,  and will  be fired when mysql  query  executed. 

I have read the doc, but no result .Hope you can solve this problem for me .Thank u.

**Comment by josephmancuso** [comment]
added this in feature/188. Will be able to use the normal logging library and then just use a file stream handler. Will write documentation for it

**Comment by josephmancuso** [comment]
https://docs.masoniteproject.com/v/v3.0/masonite-orm/installation#logging
