### ISSUE TITLE
Be able to use .primary() as for unique() constraint

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/orm#207]
Be able on a migration to use primary() this way:

```python
table.increments("user_id").primary()
```

**Comment by josephmancuso** [comment]
@girardinsamuel increments is special. Increments assumes that its the primary key. 

increments is the same as "auto incrementing primary column" version of the table so its a bit of an all-in-one. 

What we really need to to be able to specify any one of the other column types as a primary key like:

```python
table.unsigned_integer('col').primary()
```

**Comment by girardinsamuel** [comment]
@josephmancuso Yes that was a bad example but that's what I had in mind. 
And increments was confusing me I wasn't sure about what was ran under the hood. thanks for clarifying.

I will update the PR then

**Comment by josephmancuso** [comment]
ok great just making sure :)

**Comment by girardinsamuel** [comment]
I have updated the test in the PR, when I am using .primary() on a simple integer column
