### ISSUE TITLE
Error running migration with sqlite on latest version

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/orm#225]
Is it only me or ?
When I run `masonite-orm migrate` on a new sqlite database I get:
```
Starting Migration Class ..
Creating Migration Table If Not Exists ..
Running query SELECT * FROM `migrations`, (). Executed in 0.00ms

  TypeError

  argument of type 'SelectExpression' is not iterable

  at src/masoniteorm/query/grammars/BaseGrammar.py:629 in _table_column_string
      625│         Returns:
      626│             self
      627│         """
      628│         table = None
    → 629│         if column and "." in column:
      630│             table, column = column.split(".")
      631│ 
      632│         return self.column_strings.get(self._action).format(
      633│             column=column, separator=separator, table=table or self.table
```
`column` is `<masoniteorm.expressions.expressions.SelectExpression object at 0x10d7cebb0>`

**Comment by josephmancuso** [comment]
It's because of a difference in how the ORM is installed vs how it's structured locally. If you run any commands you need to run 'python orm' in the project.

**Comment by girardinsamuel** [comment]
@josephmancuso oh I was running "python masonite-orm" and with "python orm" it's working.

**Comment by Marlysson** [comment]
@josephmancuso 
I'm on Windows and until now I don't have facing with this problem. But now it come back.

Even if run "python masonite-orm" or "python orm" it's failing.

Using "masonite-orm" to create a model/migration it works fine, but in "migrate" fail.

> To install on windows:
```bash
python setup.py install
```

By run `pip install masonite-orm` accours the following errors on windows:
    - Because of pendulum version used in masonite-orm that don't support in Windows 10. ( 2.X.X )**
 
Ps: Same error that issue above.

**Comment by josephmancuso** [comment]
Make sure Masonite ORM is not installed. 

Pip uninstall masonite-orm
