### ISSUE TITLE
With statement to can use QueryBuilder or Model operations inside transaction

### ISSUE THREAD

**Issue by Marlysson** [MasoniteFramework/orm#231]
Support to run:

```python
with db.transaction("staging") as db:
    db.table('charges').update({paid: True})
```

or a Model operations:

```python
with db.transaction("staging"):
    charge = Charge.find(2)
    charge.update(paid=True)
```

The difference to #229 is that here we can run some operation outside of a transaction and rollback just some code. In #229 we can only revert couple operations.

```python

def charge(customer):
    charge = Charge.create({"customer":X , "paid":False})

    with db.transaction("staging"):
        payment = Payment.find(2)
        payment.update(value=100)
```

So, if some exception raises, just snippet inside with statement would be rollbacked. In this exemple the "history" of charges of customer would keep ( even if the payment would'nt be "done" ).

Make sense @josephmancuso ?

**Comment by girardinsamuel** [comment]
Yes could be great to use this instead of the decorator approach for some use cases.

If you think it makes sense, I can add the context manager feature to the decorator class to be able to use both

**Comment by josephmancuso** [comment]
#375
