### ISSUE TITLE
Possibility to run only a specific seed

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/orm#236]
It was possible before, and right now still documented as possible (https://docs.masoniteproject.com/v/v3.0/masonite-orm/seeding#running-seeds):
```
masonite-orm seed:run User
```

But it's not anymore, any reasons that it has been removed ? Should we add it again ?

**Comment by josephmancuso** [comment]
Nope this should still be a thing

**Comment by girardinsamuel** [comment]
Okay I will add it again (should be in git history)

**Comment by josephmancuso** [comment]
It could be. I may not have added it to ORM. With Masonite I had a wrapper around Orator to do this. We may need to just do this from scratch

**Comment by girardinsamuel** [comment]
Oh okay well I'll look into it 😉
