### ISSUE TITLE
Add table.soft_deletes() to ease working with soft delete scope

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/orm#238]
Add soft_deletes() method to blueprint to create a `deleted_at` datetime nullable column.

**Comment by Marlysson** [comment]
@girardinsamuel this?
https://github.com/MasoniteFramework/orm/blob/86e93c18940c232669a734665a857390351acc8d/src/masoniteorm/schema/Blueprint.py#L424

**Comment by girardinsamuel** [comment]
Oups it's already there ! 🤫
