### ISSUE TITLE
Add list_table_columns to schema builder

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#240]
needs a way to list the table columns so we can rework the model:doctstring command.

In order it was called `list_table_columns`:

example in orator:

```python
            conn = (
                DB.connection(self.option("connection"))
                .get_schema_manager()
                .list_table_columns(self.argument("table"))
            )
```

**Comment by josephmancuso** [comment]
we already have something like this for schema migrations. Its inside the platform classes called `get_current_schema`. Just really need to make sure its capable of getting the information we need to be able to get column names, values and enough to generate something like this:

```python
"""Model Definition (generated with love by Masonite)

    id: integer default: None
    name: string(255) default: None
    email: string(255) default: None
    password: string(255) default: None
    remember_token: string(255) default: None
    created_at: datetime(6) default: CURRENT_TIMESTAMP(6)
    updated_at: datetime(6) default: CURRENT_TIMESTAMP(6)
    customer_id: string(255) default: None
    plan_id: string(255) default: None
    is_active: integer default: None
    verified_at: datetime default: None

"""
```

**Comment by Marlysson** [comment]
We really need call database to get table informations or just all Column objects inside Bluprint already works to do this?

**Comment by josephmancuso** [comment]
The platform class does this already for sqlite because sqlite has almost no altering abilities. For SQLite we need to actually drop the table and rebuild the table on most table altering operations so you can see how we did this in the sqlite platform class. We really just need to add this to this to the other platform classes and make sure it has all the information in the model docstring that orator had
