### ISSUE TITLE
Be able to specify migration path for migrations

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#254]
Currently, databases/migration is hard coded in the migration class. Should be able to specify one in any migration commands that require it

**Comment by Qubhis** [comment]
Hi,

what about keeping migration_directory argument with slash notation when assigning it to self.migration_directory, replace hardcoded "databases/migrations" with self.migration_directory in relevant methods, and finally creating a migration_directory variable with dot notation where is needed:
```python
25   self.migration_directory = migration_directory    # "databases/migrations"
```
```python
51 + 95  directory_path = os.path.join(os.getcwd(), self.migration_directory)
```
in methods def locate + def migrate -> create variable migration_directory = self.migration_directory.replace("/", ".") which will be then passed to the pydoc.locate() call

**Comment by josephmancuso** [comment]
@Qubhis yeah that will work
