### ISSUE TITLE
Field access Expression outside of model instance

### ISSUE THREAD

**Issue by Marlysson** [MasoniteFramework/orm#264]
**Case:**

```python
inventory = Inventory.find(1)
inventory.update(price=inventory.price * inventory.discount)
```

Currently the way to do that is access the attribute from a previously loaded model 

**Solution:**

```python
inventory = Inventory.find(1)
inventory.update(price=F('price') * F('discount'))
```

Reference:

https://docs.djangoproject.com/en/3.1/ref/models/expressions/#f-expressions

**Comment by josephmancuso** [comment]
This will need to do a few things:

* Add a new `FieldExpression` class. which really just queries the table for the one column and return that value
* Somehow know the "context" in which its being used so it can set the correct connection and table. So see the example above where its used with the Inventory model.
* Simply make a query like `select price from inventory where id = 1` and return the value of price

**Comment by josephmancuso** [comment]
Looking at this now i don't think the FieldExpression class is the way to go.

For now i added the `Raw` expression.

https://orm.masoniteproject.com/query-builder#raw-queries

```python
inventory = Inventory.find(1)
inventory.update({"total": Raw("price * discount"))
```
