### ISSUE TITLE
Missing 'like' and 'not like' operator in QueryBuilder

### ISSUE THREAD

**Issue by circulon** [MasoniteFramework/orm#265]
I wanted to use the 'like' operator in where (with wildcard specifiers % and _) in postgres.

eg 
builder = SomeModel.get_builder()
builder.where('name', 'like', '%jones%')
results = builder.get()

Unfortunately these operators are not listed in the   QueryBuilder._extract_operator_value as a valid operator

Unless there is another way to do a 'like/Not like'?

Thanks

**Comment by josephmancuso** [comment]
hmm how did this get missed? lol. Thanks for reporting it

**Comment by circulon** [comment]
Np thanks for this updating this regularly

**Comment by josephmancuso** [comment]
This is completed and released in 0.9.2
