### ISSUE TITLE
QueryBuilder where_raw bindings parameter not used

### ISSUE THREAD

**Issue by circulon** [MasoniteFramework/orm#267]
As far as I can see the QueryBuilder.where_raw accepts a tuple as the values that would be bound to the parameters (?) in the final query.

The bindings parameter is not used when adding to the self._wheres attribute

Thanks

**Comment by josephmancuso** [comment]
Great point

**Comment by josephmancuso** [comment]
Good catch. Looks like the bindings were not being passed to the query expressions class

**Comment by josephmancuso** [comment]
This is fixed and released in 0.9.2
