### ISSUE TITLE
updated_at timestamp gets current timestamp on model find/hydrate when record field is empty

### ISSUE THREAD

**Issue by circulon** [MasoniteFramework/orm#268]
when using the default for the _timestamps_ attribute the updated_at attribute gets populated with the current timestamp if it is empty/null when selecting amodel record that has never been updated 
thus providing a false positive of its actual "updated_at" status

The desired  behaviour is to reflect the record field value ie None when populating a model object and the record field is empty 

Currently having to disable auto handling of timestamps as queries based on updated_at sorting are not accurate.

**Comment by josephmancuso** [comment]
@circulon can you give me some code examples of how to replicate this?

**Comment by josephmancuso** [comment]
when trying to replicate this it looks like I came across and issue where the updated_at was not even getting set when updating a record

**Comment by josephmancuso** [comment]
I think what you are saying that if record ID 1 has updated_at as NULL and you fetch the record it will actually hydrate as the current time stamp.

Can you try again on latest version of the ORM? I think this may have been fixed already

**Comment by circulon** [comment]
Yes thats exactly what I mean.

I'm at work and will add and will test once im home and report back.

**Comment by circulon** [comment]
@josephmancuso 

Confirmed this issue is fixed in the current 0.9.1 release
Thanks for checking

**Comment by josephmancuso** [comment]
Ok cool. Yeah this was fixed in 0.9.0

> Fixed issue where dates were defaulting to today's date

**Comment by josephmancuso** [comment]
Thanks for pointing this out
