### ISSUE TITLE
FirebirdSQL feature support

### ISSUE THREAD

**Issue by qlixes** [MasoniteFramework/orm#273]
Dear Sir,

I interested with your hardworked project for drop in replacement of OratorORM.
I want to join on FirebirdSQL support feature, because i like to learn for Firebird 3 and Firebird 4.
But I'm not strong on python 3 and still need knowing CodeStyle or Linter's team used.
Many thanks.
hopefully I'm not offend too many with my less power.
Thank you a lot

**Comment by josephmancuso** [comment]
Thank you for your interest in the project and feature request. I would love for the ORM to support FirebirdSQL

Unfortunately I do not want this as part of the core library as I do not want to over reach and support more than the databases supported currently. (mysql, Postgres, sqlite and mssql). 

Although most of the code is abstracted out and new databases are relatively small, new features will need to be manually tested across all different databases to ensure correct functionality.

With that being said I am open to helping you integrate firebird with this ORM if you want to open a new repository and maintain that library on your own time. You could have a library like `masonite-orm-firebird`. The ORM is very modular and can easily register new database connections. 

In your own repo you really just need a handful of classes to make the connection work.

If you are interested in doing that let me know and I can give you some more direction and some examples.

**Comment by qlixes** [comment]
Thank you a lot for reply.
Absolutely interested for it.
I'll try my best on masonite-orm-firebird.
Once again, thank you a lot

**Comment by josephmancuso** [comment]
Ok let me know when the GitHub repository is open and I can give my help on how it should be structured and the classes you will need to implement.

There are 4 databases supported here so you could just copy the classes from here for a database like Postgres to your repo and then change the naming and implementation.

After you add that you will just need to register the connection to the ConnectionResolver class which is pretty simple. Once you register that connection to the connection resolver then anybody can use your driver. Really simple.

**Comment by josephmancuso** [comment]
Just note, a quick research for python and firebird support shows some DBAPI packages only support 3.8+. This package supports 3.6+ so either create an implementation that supports Python 3.6+ or put only supports 3.8+ in your library documentation

**Comment by qlixes** [comment]
Yes, Sir. Noted.
I'll do my best.

**Comment by josephmancuso** [comment]
I'm gonna close this issue but feel free to comment here if you need help or join the slack channel
