### ISSUE TITLE
Add new builder method scopes for soft deleting 

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#276]
Need to add the following scopes or methods to the `SoftDeletesMixin` class:

* `only_trashed()`
* `restore()`
* `force_delete`

**Comment by girardinsamuel** [comment]
Yeah that's exactly what I was looking for the pingcrm inertia demo ! 

I am struggling to get only trashed users as we should check that users have a `deleted_at` field not null or not empty.. => `where_not_null("deleted_at")`  does not seem to work, I guess that the default value for `deleted_at` is not the SQL `NULL` but maybe "" ?

**Comment by girardinsamuel** [comment]
I will open a PR

**Comment by josephmancuso** [comment]
This is done
