### ISSUE TITLE
Add when to query builder

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#277]
We should be able to specify a `when` method that receives a conditional and then optionally calls the lambda or function callback:

Example:

```python
age = 25

User.when(age >= 18, lambda q: q.where('age_restricted', 1))
```

**Comment by Marlysson** [comment]
Is it like a chain of where methods?

**Comment by josephmancuso** [comment]
yeah it can be chained. Its just if the first parameter is truthy then run the callback in the second parameter. Would look something like this:

```python
# QueryBuilder

def when(conditional, callback):
    if conditional:
        callback(self)
    return self
```

**Comment by Marlysson** [comment]
A doubt, the attribute "age" in "when" method... is it evaluate from conditional from outside model or every line that checks every line from User model where age it's >= 18 and in case truthy then run callback method?

**Comment by josephmancuso** [comment]
No its just a normal conditional. Maybe a more obvious use case is:

```python
def show(self, request: Request):
    User.when(self.request.input('age') >= 18, lambda q: q.where('age_restricted', 1)).get()
```

Its just true or false, removing the variables will just look like this:

```python
User.when(True, lambda q: q.where('active', 1)).get()
# SELECT * FROM `users` WHERE `active` = '1'

User.when(False, lambda q: q.where('active', 1)).get()
# SELECT * FROM `users`
```
