### ISSUE TITLE
Custom message in logging queries

### ISSUE THREAD

**Issue by Marlysson** [MasoniteFramework/orm#285]
Define a custom messsage to logging queries.

```python
formatter = logging.Formatter('%(asctime)-15s - %(module)s - %(process)d - %(thread)d- %(levelname)s - %(message)s')
I can't find relevant documents and cases
```

**Comment by josephmancuso** [comment]
https://orm.masoniteproject.com/installation#logging

**Comment by Marlysson** [comment]
@josephmancuso Can we change the current default message that are being used inside code?

**Comment by josephmancuso** [comment]
which one?

**Comment by josephmancuso** [comment]
if you mean the one that is printing out in the connection classes, that really shouldn't be there. I just put that there for now so I can easily debug things as we test it

**Comment by Marlysson** [comment]
Yep, that one! Then the message putted in formatter should be cascade until base code...
I will take a look that!

**Comment by josephmancuso** [comment]
yeah the one printing will be removed soon. You can look into adding some more options to the formatter tho. I think currently it only does query and query time

**Comment by Marlysson** [comment]
@josephmancuso What do you think of this, change the "format" of define logging to encapsulate all of initial configs:

from:

```python
logger = logging.getLogger('masoniteorm.connection.queries')
logger.setLevel(logging.DEBUG)

formatter = logging.Formatter(
    'It executed the query %(query)s'
)

stream_handler = logging.StreamHandler()
file_handler   = logging.FileHandler("queries.log")

logger.addHandler(stream_handler)
logger.addHandler(file_handler)
```

to:

```python
...
formatter = "It executed the query %(query)s" # Message with more placeholders
handlers = [logging.StreamHandler(), logging.FileHandler("queries.log")]

logger = Logger.configure(formatter, handlers=handlers)
```

**Comment by josephmancuso** [comment]
yeah that's fine

**Comment by Marlysson** [comment]
@josephmancuso this logger to logging queries will be used to all types of infos or just sql queries?

Ask this because if to just sql query just need the "info" level of log, if not, then I need create other levels.

I'll open the PR to analysis.
