### ISSUE TITLE
Add __visible__ to model serialization

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/orm#289]
Right now, when serializing a model it will put all model fields + properties (what has been defined in __append__).

I have seen that we can start from a dict given as argument of the `serialize()` method, but I have not really see a way to define how the model should be serialized without using Masonite API.

Here I just want - on the fly - to serialize e.g. the User model with three attributes: id, name, email. `name` is a property.
I feel we would like to do something like: 
```
User.find(1).serialize(["id", "name", "email"]) # {"id": 1, "name": "John Doe", "email": johndoe@example.com}
```
OR we could also add something in the model such as : `__serialized_fields__ = ["id", "name", "email"]` 

If you confirm it's not possible right now and this implementation is correct, I'll open a PR.
We should also update documentation to explain model serialization I have not seen it in orm docs.

**Comment by josephmancuso** [comment]
There is already a `__hidden__` attribute to hide any attributes that should not be serialized. Maybe we need the opposite. Maybe a `__visible__` attribute

**Comment by girardinsamuel** [comment]
I have seen it but is it only for serialization ? 
I guess use `__visible__` instead of `__hidden__` would make more sense to the user. When you read the model code you immediately see what would be available to serialization

**Comment by girardinsamuel** [comment]
I have seen it but is it only for serialization ? 
I guess use `__visible__` instead of `__hidden__` would make more sense to the user. When you read the model code you immediately see what would be available once serialized

**Comment by josephmancuso** [comment]
well if your table has 20 fields on it and you only want to hide sensitive info then you want to only specify the hidden attributes

**Comment by girardinsamuel** [comment]
Yeah sure ! So would it makes sense to be able to use one OR the other ? In the code we could use the first of those two attributes which is not empty and warn user (in the doc) that only one of them should be defined.

**Comment by josephmancuso** [comment]
yeah that's fine. I deff see a valid scenario for both. We do the same exact thing for the __fillable__ and __guarded__ attributes

**Comment by josephmancuso** [comment]
For this task we need a new attribute on the model like `__visible__ = ["email", "name", "admin"]` which will be used in the  serialization method. This will act as the opposite of the `__hidden__` attribute used in the same method

**Comment by girardinsamuel** [comment]
could do it if you want (I will have full day on Friday !) 💪

**Comment by josephmancuso** [comment]
Sure it might be too simple for you so if its not taken by someone on Friday go for it :)
