### ISSUE TITLE
Add a way to set the deleted_at column used for soft delete scopes

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#297]
Right now the `deleted_at` column is hard coded, There should be a way to override this column name.

First step is adding a new attribute to this file `src/masoniteorm/scopes/SoftDeletesMixin.py`. The attribute should be called `__deleted_at__` along with a method to fetch this attribute `get_deleted_at_column()`:

```python
class SoftDeletesMixin:
    """Global scope class to add soft deleting to models."""

    __deleted_at__ = "deleted_at"

    def boot_SoftDeletesMixin(self, builder):
        builder.set_global_scope(SoftDeleteScope())

    def get_deleted_at_column(self):
        return self.__deleted_at__
```

Then the next set of changes are in this file: `src/masoniteorm/scopes/SoftDeleteScope.py`.

Any place you see `"deleted_at"`, it should be fetched like this:

```python
return builder.remove_global_scope(self).update({builder._model.get_deleted_at_column(): None})
```

**Comment by Marlysson** [comment]
```python
builder._model.get_deleted_at_column()
```
The `get_deleted_at_column` should exist in Model file or the Model class should use the `SoftDeletesMixin` mixin ?

**Comment by josephmancuso** [comment]
@Marlysson the model class inherits the `SoftDeletesMixin`. Thats how the global scopes get applied to the model. It will be able to be accessed on the model through the inheritance.

@Marlysson this is a pretty easy task I would wait to see if someone from the community that hasn't contributed yet take this issue.

**Comment by Marlysson** [comment]
@josephmancuso it's fine.

**Comment by Marlysson** [comment]
@josephmancuso That's right.
The inheritance by mixin should stay here?

https://github.com/MasoniteFramework/orm/blob/1.0/src/masoniteorm/models/Model.py#L57

Currently there just TimestampMixin.

**Comment by girardinsamuel** [comment]
Well actually I tried it out and it's not that simple (at least for me)
The tests for soft delete are done at query builder level, without model involved, so `builder._model` is None and we cannot fetch the name of the deleted_at column. => The only place where it has been defined is when calling `soft_deletes()` in the migration file (where the default value "deleted_at" can be overriden).

```python
def _only_trashed(self, model, builder):
    builder.remove_global_scope("_where_null", action="select")
    # => builder._model is None here when using query builder and not model
    return builder.where_not_null(builder._model.get_deleted_at_column())
```

So I am not sure how to proceed then, we should maybe use a switch to fetch the column name depending if the model is defined 🤔 ? Does not look very solid to me.
You can see the changes I made in the PR below
