### ISSUE TITLE
updated_at timestamp is filled on create

### ISSUE THREAD

**Issue by circulon** [MasoniteFramework/orm#300]
Just updated to 1.0.0 YAY!

Noticed an issue when using .create that the updated_at field gets the same timestamp as created_at when  creating a new model.

Haven't had time to investigate this yet  so I'm just adding it here

**Comment by josephmancuso** [comment]
Thats correct and intended behavior. Thats how other ORM's I have used work as well

**Comment by josephmancuso** [comment]
If the updated_at is set on create then when sorting by updated_at, this way the unmodified records will be placed between the modified ones when sorting by updated_at.

We could create a way to unset this behavior via a model attribute but I would advise against it. Is there a reason you would want this?

**Comment by circulon** [comment]
Hi Joe

Thanks for the clarification on this.  I was expecting the updated_at column to be empty (NULL) on initial record creation as this would indicate it had never been updated.

As this is expected and I now understand the reasoning behind it,  You can close this issue.

Thanks for the clarification and keep up the great work.

**Comment by circulon** [comment]
Oops Didnt realise I could close this ;)

**Comment by josephmancuso** [comment]
Yeah. When I researched this a bit I found some different opinions but most were sorta closed out and made it seem like they stayed with the default behavior. To get records that are not updated you can do something like this:

```python
User.where_column('updated_at', '=', 'created_at')
```

and records updated:

```python
User.where_column('updated_at', '>', 'created_at')
```

**Comment by circulon** [comment]
Yeah I figured that out after you clarified the usage pattern

Cheers
