### ISSUE TITLE
find and get method should be able to take parameters to select only the columns

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#302]
We should be able to do something like this:

```python
user = User.find(1, ['username', 'email'])
users = User.where('admin', 1).get(['username', 'email'])
users = User.all(['username', 'email'])
```

This would just be a shortcut for a select:

```python
users = User.select('username', 'email').all()
```

and really should just check if the parameter exists and if it does, pass to select method like this:

```python
def all(selects=None):
    if selects:
        self.select(selects)
        
    # continue rest of logic
```

Apart of this feature we should prob also add support for a `__selects__` attribute that will be passed along. It should be in the same format as a normal select but a list:

```python
class User(Model):
    __selects__ = [
        "username",
        "password",
        "remember_token as token"
    ]
```

when the model first boots up it should pass these selects to the query builder

**Comment by girardinsamuel** [comment]
@josephmancuso 
Just to help me understand:

This would return a list (or a single) of data instead of a Collection then ?
```python
user = User.find(1, ['username', 'email'])  # == {"username": "johndoe", "email": "johndoe@mail.com"}
# as where
user = User.find(1) # == <app.User (1)>
```

It's a bit like `pluck` on a Collection but instead you can add more than on field and it can be used in the query directly ?

**Comment by josephmancuso** [comment]
That's correct. It's not really like a pluck it's just a select. These 2 code and use cases are the same:

```python
user = User.find(1, ['username', 'email'])
user = User.select('username', 'email').find(1)
```

and 

```python
user = User.all(['username', 'email'])
user = User.select('username', 'email').get()
```

**Comment by girardinsamuel** [comment]
I had serialization use cases in mind because I worked on it lately and was thinking about this:

we can use visible or hidden to define parameters to use in serialized representation, but what if this time we want a different list of parameters to be serialized ? I was thinking about 
```python
User.all().serialize("username", "email")
```

but here we this PR we could do:
```python
user = User.all(['username', 'email'])
```

**Comment by josephmancuso** [comment]
Apart of this feature we should prob also add support for a `__selects__` attribute that will be passed along. It should be in the same format as a normal select but a list:

```python
class User(Model):
    __selects__ = [
        "username",
        "password",
        "remember_token as token"
    ]
```

when the model first boots up it should pass these selects to the query builder
