### ISSUE TITLE
Support database URLs

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#307]
We should be able to somehow support database URL's 

postgres://user:secret@localhost:5432/mydatabasename

We should be able to discuss the best way to approach this. Maybe we either have a function that returns the information in a correct format like:

```python
# config/database.py
from masoniteorm.helpers import database_url

DATABASES = {
    'mysql': database_url(env("DATABASE_URL"))
}
```

Maybe this returns a dictionary.

Another option is maybe just adding a URL attribute, and if it exists, use that instead of all the other config options:

```python
# config/database.py
from masoniteorm.helpers import database_url

DATABASES = {
    'mysql': {
        "user": "..",
        "password": "..",
        "url": "mysql://user:secret@localhost:5432/mydatabasename"
    }
}
```

If `url` is set, use that, if not then don't use it? 

Open for discussion. Can see how other libraries do this

**Comment by girardinsamuel** [comment]
For Django there is `django-environ` package which provide an improved `env` helper:
```python
DATABASES = {
    "default": env.db(),  # here DATABASE_URL variable is looked up in environment variables
}

# or
DATABASES = {
    "default": {
		"NAME": env("DB_NAME"),
		"USER:" env("DB_USER"),
		# ...
	}
}

**Comment by girardinsamuel** [comment]
I like the first option but it has the downside to make it difficult to add other parameters such as :
```python
DATABASES = {
  "mysql": {
    "prefix": "",
    "grammar": "mysql",
    "options": {
        "charset": "utf8mb4",
    },
  }
}
```

**Comment by Marlysson** [comment]
About the ideas:

In django we set the "default" key to define all data in dictionary from connection. 
We use the [dj-database-url](https://github.com/jacobian/dj-database-url/blob/master/dj_database_url.py) to parse the url... then it return the dictionary and put all it in "default" key back. So The option of define just the url and make this lib that we will build return all dictionary necessary to connection seems make more sense to me.

```python
DATABASES = {
    "default": database_url(env("DATABASE_URL")) # mysql/sqlite/postgres
}
```

**Comment by girardinsamuel** [comment]
Yes django-environ is using dj-database-url internally ;)

**Comment by josephmancuso** [comment]
Hm maybe we can have a. mix then. I see the benefits of having both

**Comment by girardinsamuel** [comment]
I have give it a try, let me know what you think !
