### ISSUE TITLE
Add Collection Methods

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#31]

**Comment by josephmancuso** [comment]
Need to add a whole lot of collection methods like:

```
.take()
.pluck()
.first()
.chunk()
.map()
..
```

**Comment by josephmancuso** [comment]
Resources:

https://orator-orm.com/docs/0.9/collections.html#available-methods
https://laravel.com/docs/5.8/collections#available-methods

**Comment by josephmancuso** [comment]
The first step is to replicate all the Orator collection methods. 

Next steps is to additionally replicate all Laravel collection methods

**Comment by josephmancuso** [comment]
@vaibhavmule you want to take some of these methods? All the Orator ones are in the collection class as boilerplate

**Comment by Marlysson** [comment]
@josephmancuso Can I get something? or @vaibhavmule already do something...

**Comment by josephmancuso** [comment]
yeah go for it. I don't think @vaibhavmule started it yet

**Comment by Marlysson** [comment]
Can we receive an object like a dictionary on **items** variable, right?

Cause some methods should needed a key on method signature...

**Comment by josephmancuso** [comment]
Yeah it’s gonna be a few things. Like lists, dictionaries, objects, models

**Comment by Marlysson** [comment]
@josephmancuso Can the objects received by Collection be in different states?

When calling the **pluck**, **avg** and other methods that receive some key as an argument from an object inside Collection.

Example:

```python
collection = Collection([
    {'a', 3, 'b': 2, 'c': 1},
    {'a', 2, 'd': 3},
    {'a': 1, 'e'}
])

collection.pluck('b')
collection.avg('a')
```

**Comment by josephmancuso** [comment]
Yes

**Comment by Marlysson** [comment]
The Orator uses **backpack** to collection methods and Masonite uses the backpack... That said,  do all methods will be implemented scratch?

**Comment by josephmancuso** [comment]
I'm not sure. Masonite doesn't actually use backpack. Orator does.

**Comment by josephmancuso** [comment]
someone asked if we should use backpack and I haven't really looked into it

**Comment by Marlysson** [comment]
Yep, was said that it isn't sustained. We can add just some missing methods..

**Comment by ghost** [comment]
I think we need to update backpack if we need to use it

**Comment by josephmancuso** [comment]
I think we should just get al the tests down for it and then we can refactor later to use some kind of c library if it makes sense to do so. Well have the tests behind us to help on the refactor

**Comment by josephmancuso** [comment]
@Marlysson @sphinxxanxus It's important to note that Backpack was written by Sdispater who is the same person who abandoned Orator in the first place so we may either want to write something ourselves to not be dependent on his librairies anymore

**Comment by ghost** [comment]
Okay I get it

**Comment by corentinalcoy** [comment]
@josephmancuso the `pluck` method already implemented doesn't work for this
```python
collection = Collection(
            [
                {"id": 1, "name": "Joe"},
                {"id": 2, "name": "Joe"},
                {"id": 3, "name": "Bob"},
            ]
        )
collection.pluck('id', 'name')
```
And `pluck` method should return a `Collection` object in this case

**Comment by Marlysson** [comment]
@corentinalcoy It's because the current implementation accepts just one element.. to receive more than one we'll have that to change to .pluck(self, *args).

**Comment by josephmancuso** [comment]
Looks like a new feature to me

**Comment by Marlysson** [comment]
@josephmancuso Does one feature receiving one argument and other one receiving more than one like these?

```
pluck(self, attribute)
pluck(self, *attributes)
```

**Comment by josephmancuso** [comment]
yes. Most times you only want to pluck 1. What would plucking 2 do? would it pluck both or 1 or the other?

**Comment by ghost** [comment]
read this
https://laravel.com/docs/5.8/collections#method-pluck

**Comment by josephmancuso** [comment]
Oh cool. Yeah thats actually useful

**Comment by ghost** [comment]
@corentinalcoy ===  @sphinxxanxus

**Comment by josephmancuso** [comment]
@Marlysson in the doc example above the signature would look more like this:

```python
def pluck(self, attribute, key=None):
    ..
```

**Comment by ghost** [comment]
why?

**Comment by josephmancuso** [comment]
@sphinxxanxus in the laravel doc you sent the first pluck is the key to get and the second parameter is the key to use, right?

**Comment by ghost** [comment]
> @sphinxxanxus in the laravel doc you sent the first pluck is the key to get and the second parameter is the key to use, right?

No you can do `pluck('id', 'name', 'email')` that means it can take many parameters. I think it should be 
```python
def pluck(self, *attributes):
    .....
```

**Comment by josephmancuso** [comment]
@sphinxxanxus ok I'm fine with that

**Comment by corentinalcoy** [comment]
@josephmancuso, 
Sorry I was wrong. Your answer was good

> > @sphinxxanxus in the laravel doc you sent the first pluck is the key to get and the second parameter is the key to use, right?
> 
> No you can do `pluck('id', 'name', 'email')` that means it can take many parameters. I think it should be
> 
> ```python
> def pluck(self, *attributes):
>     .....
> ```

**Comment by josephmancuso** [comment]
👍

**Comment by corentinalcoy** [comment]
I will refactor `self.items` to `self._items`
