### ISSUE TITLE
Multiple Group By

### ISSUE THREAD

**Issue by jpmateo022** [MasoniteFramework/orm#329]
I would like to request if we can have multiple fields in group_by. As of now when I try

```
 query  = query.group_by('pre_job_status, post_job_status')
or
 query  = query.group_by('`pre_job_status`, `post_job_status`')
or
query  = query.group_by('pre_job_status').group_by('post_job_status')
```

I get this error.
![image](https://user-images.githubusercontent.com/26633918/105710679-674d2c80-5f52-11eb-8083-e0fce764198e.png)
![image](https://user-images.githubusercontent.com/26633918/105710775-877ceb80-5f52-11eb-99f6-d722e980b8c6.png)

**Comment by josephmancuso** [comment]
Agreed

**Comment by josephmancuso** [comment]
@jpmateo022 added a bunch of different ways to order by . These are in version 1.0.8

```python
store.order_by("name")
store.order_by("name", "desc")
store.order_by("name", "desc").order_by("employees")
store.order_by("name, employees")
store.order_by("name, employees desc") #== sorts "name" ASC order and "employees" DESC order. Neat little feature
```

Here is full docs: https://orm.masoniteproject.com/query-builder#order-by
