### ISSUE TITLE
Querying trashed model does not work

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/orm#330]
On a soft deletable User model I get this:

```python
user = User.with_trashed().find(self.request.param("user"))
# == class model 'User' has no attribute with_trashed
```
I observe also this error on the line shown in [ORM documentation](https://orm.masoniteproject.com/models#soft-deleting):
```
>>> from app.User import User
>>> User.with_trashed().all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/samuel/.pyenv/versions/pingcrm_masonite/lib/python3.9/site-packages/masoniteorm/models/Model.py", line 40, in __getattr__
    return getattr(instantiated, attribute)
  File "/Users/samuel/.pyenv/versions/pingcrm_masonite/lib/python3.9/site-packages/masoniteorm/models/Model.py", line 510, in __getattr__
    raise AttributeError(f"class model '{name}' has no attribute {attribute}")
AttributeError: class model 'User' has no attribute with_trashed
```

But the soft deletes mixin is working otherwise. For example I can do this:
```
User.where("id", 4).count() #== 0
User.where("id", 4).with_trashed().count() # == 1
```

Here is my model: https://github.com/girardinsamuel/pingcrm-masonite/blob/fix/3.0/app/User.py

**Comment by josephmancuso** [comment]
interesting. We may need to also bind the macro to the current model as well 🤔

**Comment by josephmancuso** [comment]
Or another solution would be to append the pass through to the model which append the `__passthrough__` attribute. Either solution needs to be entirely done in that `SoftDeleteMixin` class. (or maybe even the `SoftDeleteScope` class)
