### ISSUE TITLE
"YEAR" type in SQLitePlatform missing in Blueprint

### ISSUE THREAD

**Issue by Marlysson** [MasoniteFramework/orm#340]
There's no year method in Blueprint to "year" type and "YEAR" database type in SQLite.
Mapping it as VARCHAR(4) or INTEGER?

**Comment by josephmancuso** [comment]
You are right. It should map to a varchar for sqlite as there is no YEAR datatype in SQLite.

**Comment by josephmancuso** [comment]
@Marlysson I foud a few other issues with the sqlite tests. Hopefully it doesn't cause too many merge conlficts with your doc string branch

**Comment by Marlysson** [comment]
Ok. After I will pull all changes
