### ISSUE TITLE
Bug in pagination does not apply where clause 

### ISSUE THREAD

**Issue by jpmateo022** [MasoniteFramework/orm#341]
Hi,

 It seems the pagination doesn't apply the where clause wherein it returns the total items in the database.

The total field value should only be 9.

![image](https://user-images.githubusercontent.com/26633918/106027163-96f06600-6105-11eb-8cb5-431d3f4c262f.png)

The validation I made via manual SQL query
![image](https://user-images.githubusercontent.com/26633918/106027327-c1422380-6105-11eb-9dbd-e8890fef6457.png)

The total items I have in the database without filtering.
![image](https://user-images.githubusercontent.com/26633918/106027394-d1f29980-6105-11eb-868f-d94833be93e9.png)

**Comment by josephmancuso** [comment]
Yup issue is right here on line 1322:

https://github.com/MasoniteFramework/orm/blob/ca8485976443a41fbe363afecf6e948458bf658c/src/masoniteorm/query/QueryBuilder.py#L1322-L1325
