### ISSUE TITLE
serialize causing: AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by jpmateo022** [MasoniteFramework/orm#346]
Have anyone experiencing this? It seems it happens in serialize function

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/gthread.py", line 320, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.8/dist-packages/whitenoise/base.py", line 86, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/masonite/wsgi.py", line 42, in response_handler
    start_response(response.get_status_code(), response.get_and_reset_headers())
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/http/wsgi.py", line 239, in start_response
    self.status_code = int(self.status.split()[0])
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by Marlysson** [comment]
Which query are you using before the call of serialize function?

**Comment by josephmancuso** [comment]
This doesn't look like an issue with the orm but an issue with Masonite setting the response code. Can we see a code example of your controller method?

**Comment by jpmateo022** [comment]
Hi, sorry late reply. This is what I'm calling after the query.

```
            return response.json({
                'code': 200,
                'message': 'Success',
                'data': data
            },200)
```

**Comment by josephmancuso** [comment]
@Marlysson can you replicate this? This doesn't throw that error. It looks as if the response cannot get a status. in Masonite. If anything it looks like a Masonite issue 

```
File "/usr/local/lib/python3.8/dist-packages/masonite/wsgi.py", line 42, in response_handler
start_response(response.get_status_code(), response.get_and_reset_headers())
```

**Comment by Marlysson** [comment]
Sure. I'll try this.

**Comment by jpmateo022** [comment]
Thanks Guys :)

**Comment by Marlysson** [comment]
I can't replicate this error. @jpmateo022 Can you provide more about your workflow until the final response?

With this snippet everything works fine:

```python
bulk = [{
    "age": 15,
    "is_admin": False,
    "role": "TEST"
},
{
    "age": 25,
    "is_admin": True,
    "role": "DEVELOPER",
},
{
    "age": 12,
    "is_admin": False,
    "role": "SUPERVISOR",
}]

Model.bulk_create(bulk)

data = Model.all().serialize()

return response.json({
    'code': 200,
    'message': 'Success',
    'data': data
},200)
```

**Comment by jpmateo022** [comment]
Hi, I'm moving this to the masonite framework.

https://github.com/MasoniteFramework/masonite/issues/413
