### ISSUE TITLE
Add truncate() on models too

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/orm#352]
Right now we can do
```python
from config.database import DB
DB.get_schema_builder().truncate("licenses")
``` 
Would be cool to be able to do it on the model
```python
License.truncate()
```

**Comment by jpmateo022** [comment]
> Right now we can do
> 
> ```python
> from config.database import DB
> DB.get_schema_builder().truncate("licenses")
> ```
> 
> Would be cool to be able to do it on the model
> 
> ```python
> License.truncate()
> ```

Agree :)

**Comment by josephmancuso** [comment]
This feature is really simple. The truncate queries just need to be added to the query grammars. Then a truncate method needs to be added to the query builder, as well as the __passthrough__ on the Model class.
