### ISSUE TITLE
add with_count() to query query builder relations

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#356]
We should be able to get the number of related records easily using a `with_count('relation')` method.

The code would look something like this:

```python
customer = Customer.with_count('paid_for_orders').first()
```

This should perform the below query:

```
select `customers`.*, (select count(*) from `orders` where `customers`.`customer_id` = `orders`.`billto_customer_id` and `orders`.`deleted_at` is null) as `paid_for_orders_count` from `customers` where `customers`.`deleted_at` is null
```

We should then be able to get the count of the paid for orders:

```python
customer.paid_for_orders_count
```

**Comment by Marlysson** [comment]
This would be as a @scope ?

```python
@scope
def paid_for_orders_count(self):
    return query.get().count()
```

**Comment by josephmancuso** [comment]
no it should be a select sub query now that we have this feature.

**Comment by josephmancuso** [comment]
https://orm.masoniteproject.com/query-builder#select-subqueries

**Comment by Marlysson** [comment]
@josephmancuso Taking a looking here, the method is `with_count('relation')` then the method `with_count('paid_for_orders')` implies that relation is just `orders` or is need to be done a 'split' to get the relation ?

**Comment by josephmancuso** [comment]
not sure what you mean? Like if someone needed to do deeper relations?

like

```python
User.with_count('phone.contacts').get()
```

like that? If so I think that would be a great idea. Little harder to do though. Maybe just start off with supporting single relations ..
