### ISSUE TITLE
MySQL not getting last inserted ID on creates

### ISSUE THREAD

**Issue by jpmateo022** [MasoniteFramework/orm#357]
Hi, I would like to request to add a function that returns the id generated from the create or insert. As of now the create function returns the created record but the id is 0.

**Comment by josephmancuso** [comment]
@jpmateo022 can you give me a code example? what database are you using? create should be returning the correct inserted ID already and should not be 0

**Comment by josephmancuso** [comment]
Tried to replicate this but could not. Will need more information on the code you're running

**Comment by josephmancuso** [comment]
@jpmateo022 do you have any code snippets? the `create({..})` should not be returning 0 for the ID.

**Comment by jpmateo022** [comment]
Ahh sorry, I'll get a sample once I'm available.

**Comment by jpmateo022** [comment]
Hi, Here is the response I got after using create

![image](https://user-images.githubusercontent.com/26633918/107753452-0d72a200-6d5b-11eb-9a26-be40a22c5d25.png)
![image](https://user-images.githubusercontent.com/26633918/107753515-2418f900-6d5b-11eb-93ef-14d686b6e158.png)

**Comment by jpmateo022** [comment]
Much better output

![image](https://user-images.githubusercontent.com/26633918/107789254-542cc000-6d8c-11eb-8430-06ef4cad10b7.png)

**Comment by josephmancuso** [comment]
hmm that's really weird .. And id is deff an auto incrementing primary key right?

**Comment by jpmateo022** [comment]
Yep it is

![image](https://user-images.githubusercontent.com/26633918/107789499-a1a92d00-6d8c-11eb-9771-a2f14823b067.png)

**Comment by jpmateo022** [comment]
Additional Info:
![image](https://user-images.githubusercontent.com/26633918/107789590-c1d8ec00-6d8c-11eb-96a9-574ee8040884.png)

**Comment by josephmancuso** [comment]
Ok thanks I'll try to replicate with this now. Maybe something to do with the big int ..

**Comment by josephmancuso** [comment]
What is the value of `data` here?

![image](https://user-images.githubusercontent.com/26633918/107753515-2418f900-6d5b-11eb-93ef-14d686b6e158.png)

**Comment by josephmancuso** [comment]
Thanks! Was able to use this info and reproduce and fix. This is fixed in v1.0.27
