### ISSUE TITLE
Migration change() bug

### ISSUE THREAD

**Issue by jpmateo022** [MasoniteFramework/orm#366]
Hi it seems there is a bug in change() function for migration.

![image](https://user-images.githubusercontent.com/26633918/106871997-d0c8fa00-670d-11eb-9481-722be18012f1.png)

Here is my migration script.
```

        with self.schema.table('config_templates') as table:
            table.string('device_type',300).nullable().change()
            table.string('template_type',300).nullable().change()

```

**What database are you using?**
- MySQL

**Comment by jpmateo022** [comment]
Yep Im using MySQL

**Comment by josephmancuso** [comment]
Fixed. Will release
