### ISSUE TITLE
Bug in seeder

### ISSUE THREAD

**Issue by jpmateo022** [MasoniteFramework/orm#367]
Hi I encounter a bug in seeder

I simply followed the guide but when I execute it. It goes to this.

```
masonite-orm seed:run AppConfig
```

![image](https://user-images.githubusercontent.com/26633918/106874259-56e64000-6710-11eb-830b-086a9cf696b2.png)

![image](https://user-images.githubusercontent.com/26633918/106874379-77ae9580-6710-11eb-9429-74c949a1e25b.png)

**Comment by girardinsamuel** [comment]
Did you create this seed file with `masonite-orm seed AppConfig` ?

**Comment by girardinsamuel** [comment]
I have reproduced your problem and found two issues:
- for now seeding a particular file does not support camelcase convention  => for now you should run `seed app_config`
- also the import inside the generated seed file is wrong (it should be `from masoniteorm import Seeder` and not `from masonite.orm import Seeder`.

If you correct those two things it will work.

**Comment by jpmateo022** [comment]
Nice! Thanks :)

**Comment by girardinsamuel** [comment]
I made a PR to fix the second issue. for the first one, the command indicates that a table name should be given and this is working.

I wonder if we should add the possibility to provide a model name instead ? 🤔

**Comment by josephmancuso** [comment]
> for now seeding a particular file does not support camelcase convention => for now you should run seed app_config

To do this we need to use the inflection library like we do with models. There a method to convert something like `AppConfig` to `app_config`
