### ISSUE TITLE
Request to add rename_column feature for schema builder

### ISSUE THREAD

**Issue by jpmateo022** [MasoniteFramework/orm#372]
In orator ORM, it has a rename_column but checking the docs it seems the feature is not yet available.

**Comment by josephmancuso** [comment]
This just isn't documented I guess 🤔

**Comment by josephmancuso** [comment]
It's actually `rename` not `rename_column`

**Comment by josephmancuso** [comment]
Added to docs https://orm.masoniteproject.com/schema-and-migrations#changes-and-rolling-back-migrations
