### ISSUE TITLE
Create Schema If Not Exists feature

### ISSUE THREAD

**Issue by jpmateo022** [MasoniteFramework/orm#373]
Hi, I would like to request if you can add a feature that creates the schema or table if not exists which is similar to the drop if exists. Thanks :)

**Comment by Marlysson** [comment]
@jpmateo022 By schema do you mean something like "public", "information_schema" or something like "create_table_if_not_exists" ?

```python
with schema.create_table_if_not_exists("table") as table:
``` 
This?

**Comment by jpmateo022** [comment]
yep something like that

**Comment by yubarajshrestha** [comment]
PR to resolve above feature.

https://github.com/MasoniteFramework/orm/pull/571

**Comment by josephmancuso** [comment]
Done in #571
