### ISSUE TITLE
default() not working

### ISSUE THREAD

**Issue by jpmateo022** [MasoniteFramework/orm#383]
I was adding a new field to my existing table and it has a default value.

![image](https://user-images.githubusercontent.com/26633918/107722728-8bfb1f80-6d1a-11eb-8978-3660f1ae4e7e.png)

But it was created in MySQL like this.
![image](https://user-images.githubusercontent.com/26633918/107722741-93bac400-6d1a-11eb-9635-b073ce34cd58.png)

**Comment by josephmancuso** [comment]
Whats your database?

**Comment by josephmancuso** [comment]
oh sorry you said mysql

**Comment by jpmateo022** [comment]
MySQL

**Comment by josephmancuso** [comment]
Thanks I see the issue. WIll push up a fix shortly

**Comment by jpmateo022** [comment]
Cool! Thanks :)

**Comment by josephmancuso** [comment]
Released a fix. 1.0.26
