### ISSUE TITLE
Feature Request to add execution of store procedures, and functions

### ISSUE THREAD

**Issue by jpmateo022** [MasoniteFramework/orm#385]
Hi, I would like to request if possible to add a function in the orm that will execute a store procedure, and function.

Thanks!

**Comment by josephmancuso** [comment]
hmm probably not. Why would you like it to look like? If you want to do a stored procedure it probably makes more sense to do a raw query.

Do you have any code snippets on what you would think would work? Not totally against the idea but it's going to require a new data structure in the project like a new `Procedure` class .

Do you have any examples of some stored procedures you're trying to convert to an ORM?

**Comment by jpmateo022** [comment]
I actually want to trigger a store procedure that generates a report when my create, update, and delete operations in my code is triggered. Though yeah, I think I can use the raw query but you might consider it in the future :)

**Comment by josephmancuso** [comment]
Oh I see so you're just executing on you don't want to build one. 

Yeah I think for now the best way to do it would be raw query. It would literally do the same thing as we would just be passing the query right off to the connection class.
