### ISSUE TITLE
Updating in bulk not working

### ISSUE THREAD

**Issue by ghost** [MasoniteFramework/orm#387]
Updating a single record is working perfectly but incase of multiple records ORM is not working.

**Query Tried but not Working**
```python
Model.where('some-column', 'column-value').update({
     'key': 'value'
})
```
```python
QueryBuilder().table('some-table').where('some-column', 'column-value').update({
     'key': 'value'
})
```

**Working Code**
```python
singleRecord = Model.where('some-column', 'column-value').first()
singleRecord.update({
    'key': 'value'
})
```

Anything I missed here?

**Comment by josephmancuso** [comment]
Can you be more specific on what the issue is? does it not update? Does it throw a query exception? 

Also which database? which version of Masonite ORM?

I tested this and could not reproduce

**Comment by ghost** [comment]
It does nothing neither issues nor warnings. And the database is also not updating. PostgreSQL, ORM Version: 1.0.21

**Comment by josephmancuso** [comment]
Also cannot reproduce.. 

Do you have the attributes you are updating in the `__fillable__` property?

**Comment by ghost** [comment]
Did you try reproducing as I have shown above? __fillable__ property is ok. I had to do the following to make it work.
```python
items = Model.where('key', 'value').get()
for item in items:
   item.update({
       'key': 'value'
   })

```

**Comment by josephmancuso** [comment]
Here Is my code I'm using to reproduce:

<img width="401" alt="Screen Shot 2021-02-15 at 10 59 13 PM" src="https://user-images.githubusercontent.com/20172538/108016843-73705b00-6fe1-11eb-9e8b-266aad3c6732.png">

Here is the query it generates:

```sql
UPDATE "users" SET "name" = %s, "updated_at" = %s WHERE "name" = %s, ['John', '2021-02-16 03:57:15', 'Joe']. Executed in 0.00ms
```

Here is my database before:

<img width="440" alt="Screen Shot 2021-02-15 at 10 57 09 PM" src="https://user-images.githubusercontent.com/20172538/108016790-52a80580-6fe1-11eb-94ce-b3d36e6fb3b7.png">

Here is my database after:

<img width="366" alt="Screen Shot 2021-02-15 at 10 57 26 PM" src="https://user-images.githubusercontent.com/20172538/108016804-5a67aa00-6fe1-11eb-9e33-2794b73acab4.png">


What am I doing wrong here?

**Comment by ghost** [comment]
Everything is working perfectly in yours. What is happing with mine? I will do some tests and will let you till then I will just close the issues because it's working in there.
