### ISSUE TITLE
Polymorphic and many to many polymorphic relations

### ISSUE THREAD

**Issue by holic-cl** [MasoniteFramework/orm#391]
**Describe the feature as you'd like to see it**
Add support to polymorphic and many to many polymorphic relations

**What do we currently have to do now?** 
Give some kind of **morph_many**, **morph_to** and **morph_one** annotations to give polymorphic relations support

**Comment by ninjrdevelop** [comment]
Subscribing to this, so I can migrate to MasoniteORM once it's available.

**Comment by girardinsamuel** [comment]
Just to update the state of this issue, for now Masonite ORM:
- supports **One to Many** polymorphic relationships even if not documented yet.
- does not support **Many to Many** polymorphic relationships (not implemented yet).

**Comment by ninjrdevelop** [comment]
Any luck with this since April?

**Comment by josephmancuso** [comment]
Nothing to update at this time
