### ISSUE TITLE
conda support

### ISSUE THREAD

**Issue by wwood** [MasoniteFramework/orm#397]
Hi,

Looking to test out masonite but it'd be helpful if it was on conda, as orator is.
Thanks.

**Comment by josephmancuso** [comment]
￼do you know how to do this? Is this something we can add to the GitHub action? Last time I used Conda it completely messed up my computers environments lol

**Comment by wwood** [comment]
Hi Joseph,

I have no idea about GitHub actions I'm afraid. I'm quite surprised conda messed up your environments. I use miniconda and that is quite lightweight - just a folder in your home directory and a few lines in your bashrc.

However, I don't think an install of conda locally is required - you can just follow the instructions here - fork a repo then make a PR back with changes, then the automated CI does the testing.
https://conda-forge.org/#about

HTH, ben

**Comment by josephmancuso** [comment]
Ok thanks I’ll take a look. Hopefully I can just add it to the CI pipe to upload to conda

**Comment by josephmancuso** [comment]
As an update, I am working on this. I made an anaconda account and added the build and upload as an action on the CI. So when i upload a release it will upload a build to Conda as well. I ran into some issues I think I can still work out but it did take over an hour just to attempt and upload of 1 package ...

**Comment by josephmancuso** [comment]
Figured this out. Was a me issue ... Here you go:

<img width="987" alt="Screen Shot 2021-03-05 at 9 39 40 PM" src="https://user-images.githubusercontent.com/20172538/110192328-56b68e80-7dfb-11eb-9bd2-6c6d6916c667.png">

```
conda install -c masonite masonite-orm
```

**Comment by wwood** [comment]
excellent. Thanks.
