### ISSUE TITLE
Add ability to infer the table name

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#40]
right now you need to set the `__table__` attribute. we need to be able to figure it out with the table name.

For example, the `User` model would be `users` table

**Comment by josephmancuso** [comment]
This should be pretty simple. Anywhere we use the `__table__` attribute we need to abstract it out to a method

**Comment by josephmancuso** [comment]
We just need to make a `get_table_name()` method.

The method should either look if the `__table__` attribute is set or else it should get the name of the class with an `s` appended at the end of it.

**Comment by josephmancuso** [comment]
Taking this issue for the live broadcast

**Comment by Marlysson** [comment]
Does If the table name already has the "s" at final? There's some problem?

**Comment by sdispater** [comment]
For your information, plurals are not as simple as adding a `s` at the end of the class name.

That's why for Orator I used the [inflection](https://github.com/jpvanhal/inflection) library, in particular the `tableize` function: https://github.com/sdispater/orator/blob/0.9/orator/orm/model.py#L57

**Comment by josephmancuso** [comment]
@sdispater good point. I’ll take a look at that. That brings up another point about studdlycase. Like CompanyAddresses that should default to “company_addresses”
