### ISSUE TITLE
Object of type date is not JSON serializable

### ISSUE THREAD

**Issue by ghost** [MasoniteFramework/orm#404]
```python
table.date('dob') # migration content
```

```python
model_data = Model.get()
model_data.serialize(); # throws error
```

![image](https://user-images.githubusercontent.com/67942433/109764910-3bd9f380-7c1c-11eb-8fe2-1745a48a301b.png)

**Comment by josephmancuso** [comment]
Do you have the `dob` inside the `__dates__` list on your model?

Should have something like this:

```
class User(Model):

    __dates__ = ['dob']
```

**Comment by circulon** [comment]
I had the exact same issue as @meyubaraj 

After digging into the base Model and found the __dates__ as @josephmancuso notes, all my date columns are handled as expected. 

This was not obvious to begin with though.
@josephmancuso  does this need noting in the documentation?

**Comment by josephmancuso** [comment]
@circulon https://orm.masoniteproject.com/models#dates

**Comment by josephmancuso** [comment]
@circulon is there a way I can make this more obvious in the docs? Maybe a different place for it?
