### ISSUE TITLE
QueryBuilder: .to_sql() used before .get() produces unexpected results

### ISSUE THREAD

**Issue by circulon** [MasoniteFramework/orm#406]
**Describe the bug**
Sometimes during debugging you want to see the query and the results generated by that query.

If you use .to_sql() before .get() you will get strange and incorrect results.
If you use .get() followed by .to_sql() you get the expected results.

This could cause major issues if .to_sql is used in this way in production systems.

**To Reproduce**

For this example assume table_a has 4 rows

```
        builder = (
            QueryBuilder()
            .from_raw(table_a)
            .count("id as row_count")
            .avg("rating as rating_avg")
            .max("rating as rating_max")
            .where("user_id", "=", "some uuid")
        )
        print("query: {}".format(builder.to_sql()))
        result = builder.get()[0]
        print("result: {}".format(result))
```
Produces results similar to this
**NOTE:** the results of the count field varies if you change the query slightly.
eg .max() to .min() 
```
query: SELECT COUNT(table_a."id") AS row_count, AVG(table_a."rating") AS rating_avg, MAX(table_a."rating") AS rating_max FROM table_a WHERE table_a."user_id" = 'some uuid'
result: RealDictRow([('row_count', 99), ('rating_avg', 57.28), ('rating_max', 68.64)])
```

alter the query to do .to_sql() after .get() produces expected results
```
        result = builder.get()[0]
        print("result: {}".format(result))
        print("query: {}".format(builder.to_sql()))
```
Produces 
```
result: RealDictRow([('row_count', 4), ('rating_avg', 22.28), ('rating_max', 41.64)])
query: SELECT COUNT(table_a."id") AS row_count, AVG(table_a."rating") AS rating_avg, MAX(table_a."rating") AS rating_max FROM table_a WHERE table_a."user_id" = 'some uuid'
``` 

**Expected behavior**
.to_sql should not influence the output result 

```
query: SELECT COUNT(table_a."id") AS row_count, AVG(table_a."rating") AS rating_avg, MAX(table_a."rating") AS rating_max FROM table_a WHERE table_a."user_id" = 'some uuid'
result: RealDictRow([('row_count', 4), ('rating_avg', 22.28), ('rating_max', 41.64)])
```

**Desktop (please complete the following information):**
 - OS: Mac OSX 
 - Version Catalina 10.15.7

**What database are you using?**
 - Type: Postgres 
 - Version 10.5
 - Masonite ORM  v1.0.33

**Additional context**
Any other steps you are doing or any other related information that will help us debug the problem please put here.

**Comment by josephmancuso** [comment]
Good catch. I just fixed this in version 1.0.35. Depending on when you read this it might need a few minutes to propagate to PYPI

**Comment by circulon** [comment]
Sweet!  
This had me super confused for a good couple of hours, even to the point where I was considering destroying my entire dev stack!

Keep up the great work!

**Comment by circulon** [comment]
@josephmancuso 

Hmm I just pulled down v1.0.35 and the issue still remains?
FWIW I cant seem to find your PR for this issue either as I am interesting in seeing how things get fixed etc?

I cannot seem to reopen this issue either ;(

**Comment by josephmancuso** [comment]
@circulon hmm thats weird. I was able to reproduce the issue and fix it. The issue (or what I believe the issue was) is that `to_sql()` will "reset" the query builder. This is mainly used so you can use the same query builder to run multiple queries even after you built it up. This was probably incorrectly on the to_sql() query.

So what was happening was you were:

1. building up the query
2. running `to_sql()` which reset the query builder (removes all the where clauses, etc) 
3. Running the `get()` method which ran the query without all the where clauses which obviously returns a different result ..

So to fix this i just removed the reset of to_sql() .. which should have fixed the issue.

**Comment by josephmancuso** [comment]
The fix i did directly on the 1.0 branch as it was a one liner 

https://github.com/MasoniteFramework/orm/commit/7645dee08596d555933f661cdd08203f652d37e9

**Comment by circulon** [comment]
@josephmancuso 

Looks like this is partially fixed.
  
 i'm using .count() in the main query and inside a .add_select() for between dates.
The main queyy .count looks ok.  The results from the subselecta are still weird.  

the generated query works exactly as expecetd when I pastte it into my db util.
When I run it in my app with the .to_sql() first I get an erroneous count value.

What you said makes sense about the wheres being removed. 
My .add_select also contains .from_raw() with .where and .where_colum() and where_raw() for limiting in the sub select
These .where's may be reset in the .add_select as well as part of the to_sql()?

Hope this helps

**Comment by josephmancuso** [comment]
Thanks. I can take a look at this. It helps. There's 1 more query builder that gets built inside the grammar class that's used to compile that inner query. That will be the next place I look

**Comment by josephmancuso** [comment]
@circulon Ok this is also fixed for sub select and sub queries now. Sorry if this caused issues for you but it was a pretty simple fix.

**Comment by circulon** [comment]
@josephmancuso 

No worries. thanks for being responsive.
