### ISSUE TITLE
unwanted log value [datetime] False

### ISSUE THREAD

**Issue by jpmateo022** [MasoniteFramework/orm#410]
![image](https://user-images.githubusercontent.com/26633918/110273750-36a7ea80-8008-11eb-88b2-67dc9988f139.png)

Its currently being printed to M3 DB Queue. and also logged in my supervisor logs.

**Comment by josephmancuso** [comment]
@jpmateo022 Can you help me spot this by telling me which versions you are running?

**Comment by josephmancuso** [comment]
and making sure you are running the latest versions

**Comment by jpmateo022** [comment]
Yes Im using the latest masonite-orm when I encountered the bug then I downgrade to 1.0.28 it went away.

**Comment by jpmateo022** [comment]
I'm getting this on 1.0.38 (which is the latest version)

![image](https://user-images.githubusercontent.com/26633918/110821032-a51bcf80-82ca-11eb-9050-769f0f6bb837.png)

But When I switched to 1.0.28 it's not happening
![image](https://user-images.githubusercontent.com/26633918/110821200-d0062380-82ca-11eb-8afc-d748992c2882.png)

**Comment by josephmancuso** [comment]
Thanks. This is fixed in 1.0.40
