### ISSUE TITLE
Doc: Migration from 2.3 to 3.0 (queue_table)

### ISSUE THREAD

**Issue by marcelovieirahonorio** [MasoniteFramework/orm#418]
Hi,

   In the doc about migration (https://docs.masoniteproject.com/upgrade-guide/masonite-2.3-to-3.0), I think that in 'Queue Table section', about the queue_table command, would be ".table", not ".create". 
   When I changed to ".table", worked to me.

![masonite-orm-migration_doc](https://user-images.githubusercontent.com/56178491/111033081-43548600-83ee-11eb-8858-46ef5ead2195.jpeg)

Thank you.

**Comment by Marlysson** [comment]
@marcelovieirahonorio 
But was the "queue_table" already created? Cause ".table" will use some table created and ".create" will create on the fly in migration.

**Comment by marcelovieirahonorio** [comment]
@Marlysson ,
Yes. How the doc talk about upgrade from 2.3 to 3.0, I think everyone will have the table created, in this case, could be ".table" to add new fields.

And, if don't have, the migration doc needs add the other fields to table, not only the 3 fields created in 3.0, for example, __id__ , ... , .....

**Comment by josephmancuso** [comment]
this is fixed. Great spot
