### ISSUE TITLE
Create model and migration on the same command

### ISSUE THREAD

**Issue by alfonsocv12** [MasoniteFramework/orm#427]
**Describe the feature as you'd like to see it**

On the orator orm, I was used to create my model and migration add the same time with this command

`orator make:model Foo -m`

**What do we currently have to do now?** 
You have to use 2 commands like this

`masonite-orm model Foo`
`masonite-orm migration Foo --create`

**Additional context**

I believe the best way to implement this is defaulting the migration --create, most times when you create a new model you create a table.

But leaving the possibility to change for --table like this

`masonite-orm model Foo -m --table`

- [ ] Is this a breaking change?

**Comment by josephmancuso** [comment]
Something to keep in mind as well is that some people have migrations in a different directory. Especially when not using Masonite so we will have to pass the `-d` flag off as well to the migration command

**Comment by Marlysson** [comment]
But how we can distinguish -d of models directory from -d of migrations directory? Renaming it maybe?
