### ISSUE TITLE
How do I create a composite primary key?

### ISSUE THREAD

**Issue by b4oshany** [MasoniteFramework/orm#430]
**Describe the bug**
Unable to create a composite key.

**To Reproduce**
I tried:
```
table.primary(
     ['role_id', 'permission_id']
)

**Expected behavior**
Expected a composite key created in the db.

**Comment by josephmancuso** [comment]
@b4oshany I think this is a great idea. This is currently not supported but certainly can be.

Before we work on this though, can you tell me a bit more? How would a find() work for example, 

In other words, if you had something like:

```
permission_roles
------------------------
role_id | permission_id
1         2
2         3
```

How would you get the second row here?

```python
PermissionRole.find(2,3)
```
?

In other words, how would you match on the uniqueness of the primary key?

**Comment by josephmancuso** [comment]
In short term we can certainly make it possible on the schema level but not sure how we could do this at the model or query builder level

**Comment by josephmancuso** [comment]
@b4oshany This is now possible in the latest version of Masonite ORM at the schema level. This is still not really possible at the model level but I'm not sure how we'd do that.

You do it just like this:

```python
table.primary(["role_id", "permission_id"])
```
