### ISSUE TITLE
Ability to run seeders in refresh migrations

### ISSUE THREAD

**Issue by Marlysson** [MasoniteFramework/orm#434]
**Describe the feature as you'd like to see it**
Some way to run seeders in same command of migrate:refresh.

Run all seeders
```
masonite-orm migrate:refresh --seed
```

Run specific seeder
```
masonite-orm migrate:refresh --seed CustomSeeder
```

Related tasks:
- [ ] Update documentation

**What do we currently have to do now?** 
Call seeder command inside refresh migration command

- [ ] Is this a breaking change?

**Comment by girardinsamuel** [comment]
Maybe it would be cleaner/easier to do ? What do you think ?
Run all seeders
```
masonite-orm migrate:refresh --seed
```

Run specific seeder
```
masonite-orm migrate:refresh --seed CustomSeeder
```

**Comment by Marlysson** [comment]
@girardinsamuel Sure. I'll update the PR.
