### ISSUE TITLE
PostgreSQL inet,cidr and macaddr data type

### ISSUE THREAD

**Issue by rodrigopv** [MasoniteFramework/orm#442]
**Describe the feature as you'd like to see it**
Would be nice to be able to store IP addresses in inet data type

**What do we currently have to do now?** 
There's no way to manipulate IP addresses or IP networks in Masonite-ORM.

**Additional context**
ActiveRecord from Rails has 2 approaches when using `inet` and other networking-related data types:

1. map to existing ruby objects when available (like Ruby's IPAddr)
2. map to string when not

To implement this, 2 tasks can be considered:
- [x] Support using `inet`, `cidr` and `macaddr` datatype on migrations so we keep using Masonite on projects where this data type is needed. Raw queries might still be used for making use of the datatype related operators.
- [ ] Implement operators for `inet` and `cidr` datatype: this way we can eventually get rid of raw queries/prepared statements.
 
More information on datatypes: https://www.postgresql.org/docs/9.1/datatype-net-types.html

I'm pretty much new to this framework as I'm doing all kind of efforts to get rid of Rails, maybe a previous blocker would be to support database-exclusive data types, not sure how Masonite-ORM is implementing `jsonb` at the moment.

**Comment by josephmancuso** [comment]
@rodrigopv What does your second bullet point need to do? Can this be does via a cast? I'm not too familiar with IP address data types and Postgres. 

How does a raw query solve the issue now?

**Comment by josephmancuso** [comment]
This is closed but if we need that second checkbox I will reopen this
