### ISSUE TITLE
For Postgres: 'QueryBuilder' object has no attribute 'where_between'

### ISSUE THREAD

**Issue by egwald** [MasoniteFramework/orm#447]
For Postgres: 'QueryBuilder' object has no attribute 'where_between':

`    def get_pg_data_date(self, tabelle, startDate, endDate):
       
        builder = QueryBuilder().table(tabelle)
        results = builder.table(tabelle).where_between('timestamp', startDate, endDate).get()
        return results
`

**Comment by circulon** [comment]
A similar issue is discussed (and solved) here https://github.com/MasoniteFramework/orm/issues/407

**Comment by Marlysson** [comment]
This PR #50 
And the issue #49 

Talk about it too.

**Comment by josephmancuso** [comment]
The solution here could be to just alias the between method with a new where_between method

**Comment by Marlysson** [comment]
@josephmancuso The feature of between/not between is working in tests ( testing against generated sql is fine ) but when calling by QueryBuilder or Model it fails.

I suspect that **q_mark()** method isn't marking sql to fill with bindings. I'm seeing this, but is odd..

In QueryBuilder when in .get() method is changed to the following snippet works:

```
def get(self, selects=[]):
        """Runs the select query built from the query builder.

        Returns:
            self
        """
        self.select(*selects)
        -> bindings = self._bindings # Preserving the bindings ( because to_qmark() reset it )
        result = self.new_connection().query(self.to_qmark(), bindings)

        return self.prepare_result(result, collection=True)
```

Just in couterpart a bunch of tests failing haha

**Comment by josephmancuso** [comment]
I don't understand? There should be no where_between method. The correct method is called between. 

builder.between()

**Comment by Marlysson** [comment]
You're right. The builder.between() in tests are working because it are tested against in sql grammar, but then it is ran using some database it fail.
