### ISSUE TITLE
Documentation - Collections - Available Methods anchor links are incorrect.

### ISSUE THREAD

**Issue by liquidgenius** [MasoniteFramework/orm#451]
**Describe the bug**
At [https://orm.masoniteproject.com/collections#available-methods](https://orm.masoniteproject.com/collections#available-methods) the Available Methods anchor links do not include /collections and so do not work correctly.

**Example**
https://orm.masoniteproject.com/#all
SOULD BE
https://orm.masoniteproject.com/collections#all

**Comment by liquidgenius** [comment]
I pulled the project, but cannot locate where the documentation file is located Can you direct me to this file?

**Comment by josephmancuso** [comment]
https://github.com/masoniteframework/orm-docs

**Comment by liquidgenius** [comment]
Closing as this is specific to documentation. Opened in documentation project.
