### ISSUE TITLE
Missing Documentation for Model.save() method

### ISSUE THREAD

**Issue by floriankick** [MasoniteFramework/orm#452]
In the [documentation of masonite-orm](https://orm.masoniteproject.com/) save() method to persist a models current state is not described.

I was looking for it because I know it from Eloquent, so expected it to exist in masonite-orm as well.
Actually the Model class supports it, but in the docs it is only mentioned once within a code example for collections each() function.

If you search for the word 'save' in the documentation, there are no helpfull results.
![image](https://user-images.githubusercontent.com/1364179/117438553-fdb9c280-af31-11eb-8a69-7f50226f35e4.png)

Please add a section about the save() method somewhere. At least in the code examples for dirty attributes I would expect the save() beeing called. But maybe it should be explained even further up in the Models documentation.

**Comment by Marlysson** [comment]
@floriankick The save method is just receive a model and put it as first parameter. Are you wish know about some more detailed thing ?

About dirty attributes there a section that explain it: https://orm.masoniteproject.com/models#attributes

**Comment by josephmancuso** [comment]
Added
