### ISSUE TITLE
automic expressions supporting

### ISSUE THREAD

**Issue by erhuabushuo** [MasoniteFramework/orm#455]
Masonite ORM currently does not have automic expressions

**Comment by Marlysson** [comment]
@erhuabushuo Can you provide an example about this expressions?
If you are talking about atomic/operations inside a transaction we have a section about it:

https://orm.masoniteproject.com/installation#transactions

Let me know wheter it' what you're finding?

**Comment by erhuabushuo** [comment]
like sqlachemy:

    class SomeClass(Base):
        __tablename__ = "some_table"
    
        # ...
    
        value = Column(Integer)
    
    someobject = session.query(SomeClass).get(5)
    
    # set 'value' attribute to a SQL expression adding one
    someobject.value = SomeClass.value + 1
    
    # issues "UPDATE some_table SET value=value+1"
    session.commit()

**Comment by erhuabushuo** [comment]
user = User.find(2)
    user.balance = field('balance') + 1
    user.save()
    
    UPDATE "users" SET "balance" = "balance" + 1 WHERE ID = 2

**Comment by Marlysson** [comment]
@erhuabushuo 

For the first case you can do this by using `.increment/.decrement ` methods, so you can pass some value to increment the value

`builder.table("table").increment("column", value)`

https://orm.masoniteproject.com/query-builder#increment

For the second one, we have this way to do this, by using raw expression to perform operation:
https://github.com/MasoniteFramework/orm/issues/264#issuecomment-770326853

Let'me know if these way is useful for your problem.

**Comment by josephmancuso** [comment]
Should just be as simple as adding `FOR UPDATE` and `LOCK IN SHARE MODE` at the end of queries using the builder and grammar classes.

Orator had this: 

https://orator-orm.com/docs/0.9/query_builder.html#pessimistic-locking

MySQL reference:

https://medium.com/@ibraheemabukaff/locking-rows-in-mysql-e84fd3bbb8cd

Postgres reference:

https://www.postgresql.org/docs/9.1/explicit-locking.html#:~:text=To%20acquire%20a%20shared%20row,transaction%20holds%20a%20shared%20lock.

**Comment by erhuabushuo** [comment]
> @erhuabushuo
> 
> For the first case you can do this by using `.increment/.decrement ` methods, so you can pass some value to increment the value
> 
> `builder.table("table").increment("column", value)`
> 
> https://orm.masoniteproject.com/query-builder#increment
> 
> For the second one, we have this way to do this, by using raw expression to perform operation:
> [#264 (comment)](https://github.com/MasoniteFramework/orm/issues/264#issuecomment-770326853)
> 
> Let'me know if these way is useful for your problem.

raw expression is useful for me,  does then model instance fetch the latest value  when updated by using raw expression
