### ISSUE TITLE
where binding expression  does not support boolean value 

### ISSUE THREAD

**Issue by erhuabushuo** [MasoniteFramework/orm#464]
.where({
   'vip': True
})

https://github.com/MasoniteFramework/orm/blob/1.0/src/masoniteorm/query/grammars/BaseGrammar.py#L625

why here ignore True binding. or we should just remove this.

**Comment by erhuabushuo** [comment]
maybe we also need `where_is('vip', True) `,  sql condition expression like  `where vip is true `  or `where vip is false `

**Comment by erhuabushuo** [comment]
maybe we also need `where_is('vip', True) `expression,  sql condition expression like  `where vip is true `  or `where vip is false `

**Comment by josephmancuso** [comment]
This is fixed in version 1.0.49.

Depending on the database it will either do `WHERE column = '1'` or if using Postgres it will do the actual boolean value `WHERE column IS True` (on boolean columns)
