### ISSUE TITLE
Question: Create a record where guarded or not fillable attributes are NOT NULL in db schema

### ISSUE THREAD

**Issue by circulon** [MasoniteFramework/orm#480]
**Describe the bug**
I want to make a couple of fields guarded aka not mass assignable.
These fields are NOT NULL and so require a value when creating a row even if its an empty string.

The __guarded__ fields and anything thats not in __fillable__ get removed during the .create method.
The .save method uses create if the record is not loaded.

So how can I create a model that has a guarded fields that are required at row creation?    
The only way I can see to do this is to put a DEFAULT value on the column in the db schema which kinda feels counter intuitive?

Maybe use an observer?

Thanks for any input or ideas
 

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Version Catalina

**What database are you using?**
 - Type: Postgres
 - Version  10.5
 - Masonite ORM v1.0.53

**Comment by circulon** [comment]
I think I'm on the right track with this by using an observer. 
As i'm only using the ORM with a flask rest api  how / where should I load observers?

The Docs say to load the observer via a Model Provider but where would I puth this initiation code?

**Comment by josephmancuso** [comment]
If you want to use the observers you can load it right on the bottom of the model definition:

```python
from some.place import YourObserver

class User(Model):
   #..

User.observe(YourObserver())
```

But I'm still not sure why you do not want to add this to the fillable property? The 2 solutions you have that you don't want to do are the ways I would do it. 

Set a default value on the table and then update the value later. I'm not familiar with the domain logic of your project but those are 2 sensible solutions to the issue.

If your column has a default value and you create a row in the table with a model, you will need to call `fresh()` to get the remaining default values.

```python
User.create({..}).fresh()
```

**Comment by circulon** [comment]
I guess I'm just a bit biased that the default value if set in the DB schema can feel hidden ie not obvious to someone who is using an orm like this as its not obvious from the code.  But thats just my opinion.

Regarding why not to use fillable, I was trying to keep a couple of id's that are only ever set at create time and never updated as they relate to ids on external systems.  
Having them in fillable implys (to me) that they could be accidentally updated if mass assigning values.

Having them in guarded and setting a default table value which can be updated but not mass assigned is probably the way to go I'm thinking.

Thanks for the info on the observers too. that kind of adding the observer to the model had not occurred to me while reading the orm docs.  

Cheers for the feedback

**Comment by josephmancuso** [comment]
If you have external ids at the time of creation I would recommend just making them fillable. The fillable attribute really only protects against sending a whole dictionary to the model. Something like this:

```
dictionary = {"field1": "value1", "field2": "value2"}

Model.create(**dictionary)
```


It doesn't protect the values in any other way. This is your software but I think the solution here is to do a default NULL.

if you don't have them at the time of creation they should be default null on the database. You can then update them later by simply assigning them values on the model which doesn't look at the fillable or guarded properties:

```python
model = Model.find(1)
model.external_id = '1234'
model.save()
```

Doing this doesn't take into account the fillable or guarded attributes
