### ISSUE TITLE
Migrations not wrapping table/column names

### ISSUE THREAD

**Issue by circulon** [MasoniteFramework/orm#503]
**Describe the bug**
When using migrations the alter queries are not wrapping table and column names correctly. This causes an issue when using a table name that is also a reserved keyword.

eg the following will produce a syntax error in postgres and possibly other engines.
In this example there is already a table created called "user"
```python
        with self.schema.create("user_profile") as table:
            table.uuid("id").default_raw("uuid_generate_v4()").primary()
            table.uuid("user_id").add_foreign("user_id.id.user").on_update('cascade').on_delete("restrict")
```
This throws a syntax error from psycopg2 like this
```
psycopg2.errors.SyntaxError: syntax error at or near "user"
LINE 1: ..._user_id_foreign FOREIGN KEY (user_id) REFERENCES user(id) O...
                                                                                                         ^
```
My initial thought was to update the "get_foreign_key_constraint_string()" to include the '"' in the appropriate spots but then looking at the other Platforms format strings none of them have their respective table/column identifiers (eg mssql is []) either.

So the other option is to use the self.wrap_table() in all the appropriate places but this makes the code slightly less readable.

@josephmancuso 
I would appreciate your input for a direction on this as it will affect all platforms at some point and I would like to put another PR to fix this in.

**Expected behavior**
The alter query that is built should have appropriately wrapped table and column identifiers

**What database are you using?**
 - Type: Postgres
 - Version 10
 - Masonite ORM latest

**Comment by josephmancuso** [comment]
Alter queries should wrap the table. Anywhere really there is a table, it should be using `self.wrap_table(table_name)`

This is specifically for the use case where you name the table `keyword` or something

**Comment by circulon** [comment]
> Alter queries should wrap the table. Anywhere really there is a table, it should be using `self.wrap_table(table_name)`
> 
> This is specifically for the use case where you name the table `keyword` or something

Thanks @josephmancuso 
Yeah that makes sense.  After thinking about this further I realised that the format strings are a command layout vs a specific formatting per grammar for the values to be input.

ok so I will put a PR together to make this more robust.
This will then bring them inline with how the QueryBuilder wraps tables and columns.

Cheers for the input

**Comment by circulon** [comment]
@josephmancuso 
I have added a PR #505 to address this issue
