### ISSUE TITLE
Migrate and rollback by name

### ISSUE THREAD

**Issue by tpow** [MasoniteFramework/orm#516]
I frequently have multiple migrations for various parts of my project in development at once. 

At the moment, it is awkward to avoid running all of them because craft migrate runs all that are not yet applied by default. I typically move the undesired or incomplete migration files out of the directory, run craft migrate to do the ones I want, and then put the others back to continue development.

It would be nice if I could pass a filename to the migrate command and it would run that one file (if it hasn't already been run). Similarly, craft migrate:rollback should allow rollback by name instead of the entire batch.

(Additionally helpful and somewhat related would be adding a `craft migrate:status` command that shows which have been run or not. I was thinking this already existed or may be shown as a side effect of running other commands, but perhaps I'm thinking of the ruby on rails equivalents.)

**Comment by tpow** [comment]
Ah ha! I discovered the command `masonite-orm migrate:status` exists and does what I want as mentioned in my parenthetical. However, migrate:status isn't available through craft at the moment. I didn't think that there would be a difference between the craft commands and what's exposed through masonite-orm.

**Comment by Marlysson** [comment]
@tpow You can separate you databases/migrations by each folder that your system have, example: payment, cart, items.. and when create, migrate, refresh, reset passing the -d flag to indicate migrations' directory of each part of your system and so ran each separated migration in your system. In this way you can to decrease the overkill of each handle of migration.

Some hands-on:

1. To create your models

```
masonite-orm model Order
masonite-orm model Payment
```

2. Create folders inside of databases/migrate and point migration created to each folder.:

```
masonite-orm migration create_order_table -c order -d databases/migrations/order
masonite-orm migration create_payment_table -c payment -d databases/migrations/payment
```

3. To run migration in each folder pass the -d flag in migrate command:

```
masonite-orm migrate -d databases/migrations/order
masonite-orm migrate -d databases/migrations/payment
```

In this way you only will run the specific migrations. Each command has the -d flag to indicate target directory.

**Comment by Marlysson** [comment]
@josephmancuso @girardinsamuel What you think of create concept of --tag ( under the hood would use -d flag to indicate folder ) to separate "each part of system" in migrations folder, just as handle all migration operations, then when run would be:

```
masonite-orm migration --tag payment ....
masonite-orm migrate --tag payment ....
masonite-orm refresh --tag payment ....
```

Or the use of -d flag and handling create of folders already just "solve the problem"?

**Comment by Marlysson** [comment]
@tpow Along the suggestion above, there's a PR for your exact request.

**Comment by josephmancuso** [comment]
@Marlysson I think the tag concept is a good idea
