### ISSUE TITLE
Where_Raw follow by where

### ISSUE THREAD

**Issue by felipehertzer** [MasoniteFramework/orm#540]
**Describe the bug**
When I use the where_raw function and then the where/where_ir function.. it is adding the logical operation 'WHERE' twice in SQL.

**To Reproduce**
```python
builder.where_raw("`age` = '18'").where("name", "=", "James").to_sql()
```
```sql
SELECT * FROM `users` WHERE `age` = '18' WHERE `users`.`name` = 'James'
```

**Expected behavior**
```sql
SELECT * FROM `users` WHERE `age` = '18' AND `users`.`name` = 'James'
```

**Desktop (please complete the following information):**
 - OS: Mac OSX

**What database are you using?**
 - Type: MySQL - MariaDB
 - Version 10.4
 - Masonite ORM v1.0.65

**Comment by josephmancuso** [comment]
Ah! This is an easy fix.

Need to add a missing `loop_count += 1` on this line!

https://github.com/MasoniteFramework/orm/blob/0cb558c683198628800cf6a5a70b42c57430a88b/src/masoniteorm/query/grammars/BaseGrammar.py#L570
