### ISSUE TITLE
Add Where NOT EXISTS - where_not_exists

### ISSUE THREAD

**Issue by felipehertzer** [MasoniteFramework/orm#541]
**Describe the feature as you'd like to see it**
Currently it is possible to use the functions where_not_in, where_not_between... it would be great a function for **where_not_exists**.

By the way, the where_exists documentation has an error, requesting the column as a parameter, where exists and a column is not used

**Current**
`.where_exists('column', lambda q: q.where(..))`

**Should be**
`.where_exists(lambda q: q.where(..))`

**What do we currently have to do now?** 
I didn't find a way to realize the not exists using functions

- [ ] Is this a breaking change?

**Comment by josephmancuso** [comment]
Agreed this should exist. I thought it did honestly lol. We can add this

**Comment by josephmancuso** [comment]
Should also be a `not_has('relationship')` method as well. (the opposite of the `has` method)
