### ISSUE TITLE
Add max, min, avg and sum tests

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#56]

**Comment by corentinalcoy** [comment]
@josephmancuso 
I am working on this the time you fix the issue with schema

**Comment by corentinalcoy** [comment]
![image](https://user-images.githubusercontent.com/51742802/77645511-3159a900-6f39-11ea-86b5-1d14f74314f0.png)
@josephmancuso The `to_sql` method or `to_qmark` not return the good request for the `first` method in the QueryBuilder. The limit you have set not work. It is set to `False`
