### ISSUE TITLE
TypeError when running `migrate:rollback`

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/orm#560]
**Describe the bug**
```
python craft migrate:rollback

  TypeError

  rollback() got an unexpected keyword argument 'config_path'

  at ~/.pyenv/versions/m4_01/lib/python3.9/site-packages/masoniteorm/commands/MigrateRollbackCommand.py:17 in handle
      13│         {--d|directory=databases/migrations : The location of the migration directory}
      14│     """
      15│
      16│     def handle(self):
    → 17│         Migration(
      18│             command_class=self,
      19│             connection=self.option("connection"),
      20│             migration_directory=self.option("directory"),
      21│         ).rollback(
```

**To Reproduce**
In a fresh Masonite 4 project with ORM 2.0.

**Expected behavior**
It should not raise error.

**Screenshots or code snippets**
Screenshots help a lot. If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: Big Sur

**What database are you using?**
 - SQLite
 - Masonite ORM: 2.0

**Comment by josephmancuso** [comment]
I don't think I have 2.0 updated on PYPI with the latest changes right?

**Comment by girardinsamuel** [comment]
No indeed, but I have installed wihout pypi direcltry from github.
Actually it's a real bug in 2.0, I am fixing it right now
