### ISSUE TITLE
Be able to set log level in connection details

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#568]
Right now its hard coded to debug but you should be able to set the log level to something like info or higher to have those logs show up or be detected somewhere

**Comment by josephmancuso** [comment]
Should also add logging for model hydration so other packages can listen

**Comment by Marlysson** [comment]
@josephmancuso How should be the api for this? 
Wouldn't be the logging from python or logger from database.py useful?

**Comment by josephmancuso** [comment]
Should just be log_level=info inside the connections config same as we have it for the logging setting. Then inside the base connection we have logging.debug(). It should be logging.{log_level}()
