### ISSUE TITLE
Add Inserting related models

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#57]
https://orator-orm.com/docs/0.9/orm.html#inserting-related-models

**Comment by corentinalcoy** [comment]
@josephmancuso Can I get this?

**Comment by josephmancuso** [comment]
@corentinalcoy this is going to be phase 3 so shouldn't be started yet

**Comment by josephmancuso** [comment]
@corentinalcoy @Marlysson @girardinsamuel I just realized we can't actually do this ticket until we figure out #151

**Comment by josephmancuso** [comment]
I think we actually can do this now because calling the related method actually returns the BelongsTo class where we can fetch the builder method and associate the records
