### ISSUE TITLE
model command PEP8 standar

### ISSUE THREAD

**Issue by alfonsocv12** [MasoniteFramework/orm#578]
**Describe the feature as you'd like to see it**
When you use the masonite-orm model command. the name that you choose for the model should comply with PEP8 on both the ClassName that is camelcase and the file snake_case

**What do we currently have to do now?** 
Currently the command creates file with CamelCase.

**Additional context**
Link to the PEP8 file naming, class naming page https://www.python.org/dev/peps/pep-0008/#package-and-module-names.

- [ ] Is this a breaking change?
For the orm no I don't know if is for the framework

**Comment by josephmancuso** [comment]
I personally like the pascal case for the file names so i am not open to change it but I would be open to adding like a `-p` flag for pep 8

**Comment by josephmancuso** [comment]
Fixed in #579
