### ISSUE TITLE
model command migration argument suggestion

### ISSUE THREAD

**Issue by alfonsocv12** [MasoniteFramework/orm#579]
**Describe the feature as you'd like to see it**
I think in most cases when you wan't to build a model and migration at the same time the migration should be creating a table.

**What do we currently have to do now?** 
Default -m argument edits existing table.

**Additional context**
This command.

```bash
masonite-orm model [model-name] -m
```

will generate this migration.

```python
"""[model-name] Migration."""

from masoniteorm.migrations import Migration


class [model-name](Migration):
    def up(self):
        """
        Run the migrations.
        """
        with self.schema.table([model-name]) as table:
            pass

    def down(self):
        """
        Revert the migrations.
        """
        pass

```

suggestion.
```python
"""[model-name] Migration."""

from masoniteorm.migrations import Migration


class [model-name](Migration):
    def up(self):
        """
        Run the migrations.
        """
        with self.schema.create([model-name]) as table:
            pass

    def down(self):
        """
        Revert the migrations.
        """
        pass

```

- [] Is this a breaking change?
No

**Comment by josephmancuso** [comment]
hmm this is wrong. @Marlysson do you want to handle this if you have some time?

**Comment by alfonsocv12** [comment]
> hmm this is wrong. @Marlysson do you want to handle this if you have some time?
I can fix this one

**Comment by alfonsocv12** [comment]
Here is the fix https://github.com/MasoniteFramework/orm/pull/582 I don't think I can linked by my self

**Comment by Marlysson** [comment]
@josephmancuso the @alfonsocv12 already taken it.
