### ISSUE TITLE
Make error more obvious when trying to create record on a missing table

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/orm#597]
For now when we create a record e.g. for a Post model, if the table does not exist yet we have:
```bash
AttributeError: class 'Post' has no attribute id. Did you set the primary key correctly on the model using the primary_key attribute?
```
instead of having the real error which is that table is missing.

**Comment by Marlysson** [comment]
This could be done in ServeCommand to stop the app of starting when there migrations to be done?

**Comment by girardinsamuel** [comment]
> This could be done in ServeCommand to stop the app of starting when there migrations to be done?

I am not sure it would be a good idea to link masonite and masonite-orm this way. Exceptions are fine. It's just the content of the exception that was not the correct one.

But finally right now I can't reproduce the issue..
