### ISSUE TITLE
REGEXP operator support for MySQL

### ISSUE THREAD

**Issue by JRubics** [MasoniteFramework/orm#617]
Hi, we would like to be able to use REGEXP when making queries on MySQL database.

Currently when we try to execute this code:
```
query.where('name', 'regexp', f'^{value}(-[0-9]+)?$') 
```
we get error:
`ValueError: Invalid comparison operator. The operator can be =, >, >=, <, <=, !=, <>, like, not like`

I think this change should be added to the QueryBuilder, Grammars (not only Mysql) and expressions (JoinClause).

- [ ] Is this a breaking change?

**Comment by josephmancuso** [comment]
Agreed. I believe we can add this pretty simply.

**Comment by josephmancuso** [comment]
Added in v2.6.0

**Comment by JRubics** [comment]
Thanks! :tada:
