### ISSUE TITLE
Accessors and mutators aren't called on SomeModel.create()

### ISSUE THREAD

**Issue by JRubics** [MasoniteFramework/orm#619]
When we want to create a model which attributes are managed through accessors and mutators, we get error like: `QueryException('(1054, "Unknown column \'some_table.username\' in \'field list\'")')`

Example of our model:
```
class SomeModel(Model):
    __table__ = 'some_table'
    __guarded__ = []
    __hidden__ = [
        'user',
    ]
    __appends__ = [
        'username',
    ]

    def get_username_attribute(self):
        return self.user.username

    def set_username_attribute(self, value):
        from .user import User
        user = User.where('username', value).first_or_fail()
        self.user_id = user.id

    @belongs_to('user_id', 'id')
    def user(self):
        from .user import User
        return User
```
and example of using it:
```
values = dict(
            username='John',
            ...
        )
s = SomeModel.create(values)
```
I think the problem is because in create method on Model class, accessors and mutators aren't called.

Desktop (please complete the following information):

    OS: Linux
    Version Ubuntu 21.10

What database are you using?

    Type: [MySQL]
    Version [14.14 Distrib 5.7.30, for Linux (x86_64) using EditLine wrapper]
    Masonite ORM [2.4.2]

**Comment by josephmancuso** [comment]
Are you sure some_table has the column? By default the user table column is just name I think. Is this different? 

A mutator wouldn't cause it to throw a `QueryException`. Could you give more context?

**Comment by JRubics** [comment]
Table some_table has a column called user_id and if I understood relationships correctly it is connected to the User model through belongs_to relationship. Please correct me if I am wrong :)
But regarding relationships, I had the same problem with just changing column name in accessors and mutators like:
```
class SomeModel(Model):
    __table__ = 'some_table'
    __guarded__ = []
    __hidden__ = [
        'user',
    ]
    __appends__ = [
        'theme',
    ]
def get_theme_attribute(self):
      return self.themes

def set_theme_attribute(self, value):
      self.themes = value
```
when table has field called themes but I want to access it like some_models.theme. Problem is that when creating some model, mutators are never called. I debugged it and added breakpoints to check it.

I think query exception is thrown because when query tries to execute, it tries to access some_model.username/some_model.theme field instead of the value from accessors and mutators. The way how query is built doesn't support this example (that were working correctly in Orator). Query is like `insert into some_table (username, theme) values (...)` instead of using join for user and themes (with s) for theme.

Is there maybe some other way to archive this that id different from the orator way?

**Comment by josephmancuso** [comment]
I don't believe the mutators should be called on create. The mutators are more wrappers around setters and getters.

So mutators are called here when you do `model.theme = "something"`.

**Comment by JRubics** [comment]
Okay, thank you, I will try than to move this code from mutators to some other place :) Maybe this should also be mentioned in the docs [here](https://orm.masoniteproject.com/orator-to-masonite-orm) to be clear when switching from otator to masonite-orm :)
