### ISSUE TITLE
Empty string as default value in migrations not working [MySQL]

### ISSUE THREAD

**Issue by JRubics** [MasoniteFramework/orm#620]
In migrations when creating a schema if we add default value to string field to be empty string (`''`) and run the migrations, that field becomes NULL in the table.

Example of migration:
```
class CreateSomeTable(Migration):
    def up(self):
        with self.schema.create('some_table') as table:
            table.increments('id')
            table.string('another_field', 10).default('')
            ....
```

Desktop (please complete the following information):

    OS: Linux
    Version Ubuntu 21.10

What database are you using?

    Type: [MySQL]
    Version [14.14 Distrib 5.7.30, for Linux (x86_64) using EditLine wrapper]
    Masonite ORM [2.4.2]

**Comment by josephmancuso** [comment]
This is fixed

**Comment by JRubics** [comment]
Thank you! :slightly_smiling_face:
