### ISSUE TITLE
Migration hierarchy not working

### ISSUE THREAD

**Issue by yubarajshrestha** [MasoniteFramework/orm#626]
**Describe the bug**
If you have multiple migrations in package development then we need a way to maintain the hierarchy of migrations.

**To Reproduce**
1. Start basic package development
2. Add few migration files with relations in it
3. Try to migrate and see the order of migrations created

**Expected behavior**
Should be able to maintain the order of migrations registered.

**Comment by girardinsamuel** [comment]
Summarizing the specs to fix this issue here (from Discord):

👉  The proposed solution was to add an index in the migration filename: `{timestamp}_{index}_{name}.py`.
This index would be computed based on the list of existing migrations in the migrations folder.

@josephmancuso is that correct ?

**Comment by girardinsamuel** [comment]
@yubarajshrestha Are you okay with the specs above ?

**Comment by yubarajshrestha** [comment]
> @yubarajshrestha Are you okay with the specs above ?

Yes, you're right. You should order those migrations based_on order of migrations added in migrations.

```python
.migrations(
                "migrations/first_table.py",
                "migrations/secon_table.py",
                "migrations/third_table.py",
            )
```

**Comment by girardinsamuel** [comment]
> Yes, you're right. You should order those migrations based_on order of migrations added in migrations.

☝️ Yes you're right. But that become a Masonite issue then. I will transfer this issue to the Masonite repo.

**Comment by josephmancuso** [comment]
I think this is solve https://github.com/MasoniteFramework/masonite/blob/4.0/src/masonite/packages/providers/PackageProvider.py#L150

**Comment by yubarajshrestha** [comment]
> I think this is solve https://github.com/MasoniteFramework/masonite/blob/4.0/src/masonite/packages/providers/PackageProvider.py#L150

@josephmancuso if you try to migrate the migration with above solution that will give you error if you try migrating.
