### ISSUE TITLE
increment and decrement doesn't works

### ISSUE THREAD

**Issue by LordDeveloper** [MasoniteFramework/orm#679]
Hi, Why increment doesnt works? It must returns a boolean value, But return a QueryBuilder instance. 😦

```
from databases.models import Order

order = Order.in_random_order().first()
print(order.increment('progressed'))
```

I also tried a non-exists column, It should be raise error, But nothing happened

**Comment by Marlysson** [comment]
@josephmancuso Currently the model data is returned in updates operation, with this issue returning the boolean if a successful operation or with rows affected there's will breaking change with the api, which implement?

**Comment by josephmancuso** [comment]
@Marlysson although this technically is a breaking change, it is also a bug since it is not returning expected behavior. I think in this instance it is ok to modify this to return the new number
