### ISSUE TITLE
`seed:run` command ignores `connection` option

### ISSUE THREAD

**Issue by os-nikita** [MasoniteFramework/orm#689]
### Describe the bug

The `connection` option is available on `seed:run` (and `migrate:refresh` when used together), but this option is ignored, resulting in the default database connection always being used.

### OS

macOS

### OS version

Monterey 12.3.1

### Masonite Version

4.12.1

**Comment by os-nikita** [comment]
@josephmancuso #690 only fixed this on the `migrate:refresh` command passthrough.

The underlying issue is still that `seed:run` (SeedRunCommand's) code does not use the connection option at all from what I can tell.

<img width="679" alt="image" src="https://user-images.githubusercontent.com/92428260/172121600-1ca659f6-de86-449d-a53b-464088a82c30.png">

Would simply adding `Model.on(...)` suffice in your opinion?

**Comment by josephmancuso** [comment]
I'll update this for the seed:run as well I guess I missed that in the PR

**Comment by josephmancuso** [comment]
The best i can do right now is setting the connection on the seeder class so you can do something like this:

```python
class UserTableSeeder(Seeder):

    def run(self):
        """Run the database seeds."""
        factory(User.on(self.connection), 5).create({
            'name': 'Joe',
            'password': 'joe',
        })
```
