### ISSUE TITLE
Code completion and type hinting in IDEs?

### ISSUE THREAD

**Issue by maicol07** [MasoniteFramework/orm#695]
**Describe the feature as you'd like to see it**
A way to get code completion and type hinting in IDEs

**What do we currently have to do now?** 
No code completion/type hinting in IDEs

**Additional context**
Laravel code completion is achieved by a custom plugin (i.e. in Jetbrains PHPStorm) that adds completion: 

- [ ] Is this a breaking change?

**Comment by maicol07** [comment]
Update: it's possible to get type hinting and code completion by manually specifying fields in the class:

```python
from masoniteorm.models import Model


class WpPost(Model):
    """
    Post Model
    """

    post_title: str
```

The only downside is that you need to write them manually as class fields. An IDE plugin that gets them from the database (or from the migrations).

Also some methods (such as `first()`) are not completed in the IDE (I think they're magic methods)

**Comment by girardinsamuel** [comment]
We are currently type hinting the whole masonite codebase for Masonite 5. So we might definitely be able to do the same for Masonite ORM if we have time. This will give completion and type hint in IDE.
That's a first possible and easy improvment 😉. This should also solve `first()` (even if it's a "magic method", by adding a `.pyi` it will work).

But that won't add type hinting of model parameters. For this, we need to think about it it's not easy as everything is dynamic, I am not event sure we could do that. (I will take a look).

**Comment by josephmancuso** [comment]
To solve the model fields auto complete issue we used to have a "model:docstring" command which would just output all the model fields in the terminal and you could just copy and paste them on the model. 

We could do something like that again with M4

**Comment by girardinsamuel** [comment]
Yes sure, so there are two tasks related to this issue:
- [ ] #704 
- [ ] #705 

I am splitting it into new issues referencing this one.
@maicol7 I guess we can close this issues now.

**Comment by maicol07** [comment]
@girardinsamuel ok, so this issue is replaced by the two above?

**Comment by girardinsamuel** [comment]
> @girardinsamuel ok, so this issue is replaced by the two above?

Yes exactly. As it's two important tasks I split them into two issues to better track their progress. So you can close this issue now 😉

**Comment by maicol07** [comment]
Ok, done!
