### ISSUE TITLE
Query with where_in function returns out of list index error

### ISSUE THREAD

**Issue by leannextang** [MasoniteFramework/orm#701]
**Describe the bug**
When I called defined function with where_in(), returns out of list index error.

**To Reproduce**
1. Set Model:
    <pre><code>
    Class BillingAccountProjectContracts(Model):
    @has_one('id', 'contract_id')
    def contract(self):
        return models.Contract
    @scope
    def bbc(self, query):
        return query.where_has(
              "contract", lambda query: query.where_in("company_id", [1,2,3,4])
        )
    </code></pre>
3. call defined function:
     obj = models.BillingAccountProjectContracts.bbc().get()

**Expected behavior**
Return collection which match the conditions.

**Screenshots or code snippets**
![image](https://user-images.githubusercontent.com/103096852/171379868-e800eae5-c9b4-41df-8e0c-ae2428d40340.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey
 - Version 12.3 with Apple M1

**What database are you using?**
 - Type: Postgres
 - Version 12.10
 - Masonite ORM v2.11.9

**Additional context**
None

**Comment by josephmancuso** [comment]
Can you upgrade Masonite ORM to latest version and try again? This should have been fixed in one of the latest releases

**Comment by josephmancuso** [comment]
Can reopen if it is still an issue

**Comment by leannextang** [comment]
Had updated to v2.12.0,
but stil have the same problem...

**Comment by josephmancuso** [comment]
Ok thanks we'll look into this

**Comment by josephmancuso** [comment]
Also fixed in #709
