### ISSUE TITLE
Add dot notation for related relationships in where_has method

### ISSUE THREAD

**Issue by leannextang** [MasoniteFramework/orm#703]
**Describe the bug**
Cannot use related table in where_has function, in Orator this worked: 
     
<pre><code>
@scope
def abc(self, query): 
    return query.where_has( "contract.contract_supports", lambda query: query.where(“category”, “abc”) ).get() 
</code></pre>

how can I use it in Masonite-ORM? Is there a way to fetch this?

**To Reproduce**
1. Set Model:
    <pre><code>
    Class BillingAccountProjectContracts(Model):
    @has_one('id', 'contract_id')
    def contract(self):
        return models.Contract
    @scope
    def abc(self, query):
        return query.where_has( 
              "contract.contract_supports", lambda query: query.where(“category”, “abc”)
         ).get() 
    </code></pre>
3. call defined function:
     obj = models.BillingAccountProjectContracts.abc().get()
4. See error:
     model.BillingAccountProjectContracts doesn't have this attribute.

**Expected behavior**
Return collection which match the conditions.

**Screenshots or code snippets**
None

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey
 - Version 12.3 with Apple M1

**What database are you using?**
 - Type: Postgres
 - Version 12.10
 - Masonite ORM v2.11.9

**Additional context**
None

**Comment by josephmancuso** [comment]
I'm not sure we can do dot notation with where_has currently. We'll have to work on it
