### ISSUE TITLE
Add a "model:docstring" command to generate type hinting for models

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/orm#705]
To have type hinting for model attributes what we can do is to add a new command `model:docstring` to generate automatically type hints for the models. Then we would just have to copy/paste generated hints in our model classes.

This command existed before so we just have to write it back here. IMO it should live in the ORM codebase so that non Masonite users can benefit of it.

_Originally posted by @girardinsamuel in https://github.com/MasoniteFramework/orm/issues/695#issuecomment-1144566820_

**Comment by girardinsamuel** [comment]
It's linked to the issue #240 but not an exact duplicate. Indeed it would be great to generate a model docstring but here we need to generate the model type hints too.
So maybe generating two parts is the solution:

```python
Model Docstring:
"""Model Definition (generated with love by Masonite)
    id: integer default: None
    name: string(255) default: None
    email: string(255) default: None
    password: string(255) default: None
    remember_token: string(255) default: None
    created_at: datetime(6) default: CURRENT_TIMESTAMP(6)
    updated_at: datetime(6) default: CURRENT_TIMESTAMP(6)
    customer_id: string(255) default: None
    plan_id: string(255) default: None
    is_active: integer default: None
    verified_at: datetime default: None
"""

Type Hints:
from pendulum.datetime import DateTime
id: int
name: str
email: str
password: str
remember_token: str
created_at: "DateTime"
updated_at: "DateTime"
customer_id: str
plan_id: str
is_active: int
verified_at: "DateTime"
```

⚠️ dates/datetimes can be tricky. If declared in __casts__ parameters will be DateTime instances else it will be str instances.

**Comment by josephmancuso** [comment]
FYI This should also solve https://github.com/MasoniteFramework/orm/issues/240
