### ISSUE TITLE
Value changed in creating observer is not saved in the database

### ISSUE THREAD

**Issue by JRubics** [MasoniteFramework/orm#707]
Hi, I am using observer like this:
```python
class WebsiteObserver:
    def creating(self, website):
        website.app_name = new_name()

Website.observe(WebsiteObserver())
```
but after I do:

```python
website = Website()
...
website.save()
```

observer is called, but value is not saved in the database. If I try to call `website.get_raw_attribute('app_name')` after `save()` I get the new value, but just `website.app_name` returns the old one.

**Expected behavior**
I think it should change value to the new one, but please check if I am doing something wrong.

Desktop:

    OS: Linux
    Version Ubuntu 21.10

What database are you using?

    Type: [MySQL]
    Version [14.14 Distrib 5.7.30, for Linux (x86_64) using EditLine wrapper]
    Masonite ORM [2.4.2](https://app.tara.ai/68/*/tasks/masonite-x-inc)(https://app.tara.ai/68/*/tasks/masonite-x-inc)(https://app.tara.ai/68/*/tasks/masonite-x-inc)<br />[Tara Task]<br />[Tara Task]<br />[Tara Task]<br />[Tara Task](https://app.tara.ai/masonite-x-inc/*/tasks/68)

**Comment by josephmancuso** [comment]
cannot replicate this behavior. Could you give some more detail? what is the value of `new_name()`?

Heres what i tried to replicate:

1. observer:
<img width="426" alt="Screen Shot 2022-06-05 at 3 40 20 PM" src="https://user-images.githubusercontent.com/20172538/172067738-e775f6d5-cc1a-4da7-b755-8ed13266ebfe.png">


2. Code
<img width="639" alt="Screen Shot 2022-06-05 at 3 41 48 PM" src="https://user-images.githubusercontent.com/20172538/172067784-5997dc00-1962-4a6c-8c5e-2b72d0266643.png">

3. Result
<img width="1209" alt="Screen Shot 2022-06-05 at 3 42 22 PM" src="https://user-images.githubusercontent.com/20172538/172067794-1235def3-58d1-4752-8846-9b8bbeba16e2.png">


Looks like its working. It's also working if i don't set the name, its also working if i use the create method.

Can you tell me what else is missing that i haven't tried here?

**Comment by JRubics** [comment]
I realized I am using `with DB.transaction():` and that's why just `website.app_name` is not working until transaction get executed. Sorry, my bad :disappointed:

I still can't make it work even after the transaction. Transaction looks like this:
![tr7](https://user-images.githubusercontent.com/22733322/172177164-d43de1c8-017b-4f63-aa74-4cf8c00effc1.png)
I'm updating `vhost` after `save()` because it depends on new `app_name` value. After this, in the database `app_name` still has old value.

I managed to solve it doing this: 
![tr6](https://user-images.githubusercontent.com/22733322/172177017-e1e654e7-77d3-4990-a1cf-fee618703eae.png)
but I don't think it is the right way. Do you know what am I doing wrong?

One more note: `new_name()` is making a query to the database to check if name already exists. If it does, it adds suffix to the name. I'm not sure if that query has something to do with the transaction?

And thank you a lot for helping here :pray:

**Comment by josephmancuso** [comment]
hmm possibly. This is deff more good information so I'll go back and see if I can replicate this

**Comment by JRubics** [comment]
Thank you! :)

**Comment by josephmancuso** [comment]
v2.13.1
