### ISSUE TITLE
Cast should not be optional on create

### ISSUE THREAD

**Issue by circulon** [MasoniteFramework/orm#728]
**Describe the bug**
if you have a model thst defines attributes to be cast 
via `__casts__` you should not have to then tell `.create()` to check the model for casts on columns, it should just handle it transparently.

**To Reproduce**
```python
class SomethingModel(Model)

  __table__ = "something"

    __casts__ = {"roles": "json"}

    __fillable__ = ["roles"]
```
This implies that the `roles` column ONLY accepts JSON formatted data.

Create the model:
```python
new_something = SomethingModel.create({
    "roles": ["admin", "manager"]
})
```
This Fails with an error similar to this (in postgres):
column "roles" is of type json but expression is of type text[] LINE 1: ...ARRAY['adm... ^ HINT: You will need to rewrite or cast the expression

We should not have to remember that a particular model has specific casts on some of its columns and so do this instead:
```python
new_something = SomethingModel.create({
    "roles": ["admin", "manager"]
}, cast=True)
```
   
**Expected behavior**
The model is created and the columns that have casts are handled transparently

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Version 10.15.7

**What database are you using?**
 - Type: Postgres 
 - Version 10.15
 - Masonite ORM 2.14.0

**Additional context**
Probably should add a deprecation warning that the `cast` parameter is deprectaed as casts are now always checked

**Comment by josephmancuso** [comment]
This would have to be done in Masonite ORM 3 since this is a breaking change if we defaulted casting to true

**Comment by circulon** [comment]
> This would have to be done in Masonite ORM 3 since this is a breaking change if we defaulted casting to true

Urgh thats annoying...  
maybe adding a warning of some form that casting is set to false BUT columns were found that should  be cast. ie set `cast=True` as an interim solution?

This would then remove a lot of WTF moments during testing.

Thoughts?

**Comment by josephmancuso** [comment]
Development was completed and merged into the 3.x branch which will be deployed when we are ready to bump the major. Probably with Masonite 5 in September time frame
