### ISSUE TITLE
`RecursionError: maximum recursion depth exceeded` when using `new_from_builder()`

### ISSUE THREAD

**Issue by JRubics** [MasoniteFramework/orm#731]
After fixing [this](https://github.com/MasoniteFramework/orm/issues/682) issue, another bug occurs when calling `new_from_builder()`: `RecursionError: maximum recursion depth exceeded`

Since the previous issue was hard to reproduce, I created a small example where you can check it: https://github.com/JRubics/masonite-orm-issue-example

Steps to run it are in the `README.md`.
Be sure to test it with both `masonite-orm` `2.13.2` (old issue) and `2.13.3` (new issue)

Desktop:

    OS: Linux
    Version Ubuntu 21.10

What database are you using?

    Type: [MySQL]
    Version [14.14 Distrib 5.7.30, for Linux (x86_64) using EditLine wrapper]
    Masonite ORM [2.4.2]

**Comment by josephmancuso** [comment]
Thank you so much for building that repo. Looks like the issue was that you can't deep copy lambda expressions I guess. I changed the deep copies to shallow copies and it fixes this issue but now I need to verify it still fixes the last issue

**Comment by JRubics** [comment]
Unfortunately, it doesn't fix the previous issue. :cry:

**Comment by josephmancuso** [comment]
@JRubics which issue?

**Comment by JRubics** [comment]
https://github.com/MasoniteFramework/orm/issues/682

**Comment by josephmancuso** [comment]
hmm ok ill reopen that issue and take a look

**Comment by JRubics** [comment]
Thank you :) you can use the same example from this issue to reproduce it
