### ISSUE TITLE
Change default Model directory when creating them with the `model` command

### ISSUE THREAD

**Issue by maicol07** [MasoniteFramework/orm#749]
**Describe the feature as you'd like to see it**
Change default Model directory when creating them with the `model` command to `app/Models`
Laravel docs reference: https://laravel.com/docs/9.x/eloquent#generating-model-classes

**What do we currently have to do now?** 
Currently models are generated in the `app` directory

- [x] Is this a breaking change?

**Comment by josephmancuso** [comment]
This would have to be done in the 3.x branch. Although not a breaking change it would be a change in behavior people probably wouldn't be expecting

**Comment by josephmancuso** [comment]
Looking at the issue again I'm going to make a way to just add a parameter to the MakeModelCommand.

```python
MakeModelCommand(model_directory="app/models")
```

This way when people use the command they can set whatever defaults they need for their application. For Masonite we can probably do something like:

```python
MakeModelCommand(model_directory=self.application.make("models.location"))
```

**Comment by josephmancuso** [comment]
or it can be done with a -d flag on the command line
