### ISSUE TITLE
Model .update() does not check cast attributes

### ISSUE THREAD

**Issue by circulon** [MasoniteFramework/orm#759]
**Describe the bug**
using .update() on a model with attribute changes that have to be cast does not work.
It looks like all values are passed directly to the QueryBuilder without being transformed in any way.

**To Reproduce**
```python

class User(Model):
     __casts__ = {"roles": "json"}

    __fillable__ = [
        "name",
        "age"
        "roles",
    ]

user = User.create({
    "name": "Bob",
    "age": 26,
    "roles": ["admin"],
}, casts=True).fresh()

# now we want to update the model
user.update({
  "roles": ["std_user"],
})
```
this fails in postgres with an error similar to the following
```
column "roles" is of type json but expression is of type text[]
LINE 1: ..."roles" = ARRAY['adm...
                              ^
HINT:  You will need to rewrite or cast the expression.  
```

Current workaround is to update each attribute on the model separately and use .save() which casts the attributes to their intended column type correctly.
eg
```python
user.name = "Bobson"
user.roles = ["std_user"]
user.save()
```
But this is just less clean  if many attributes are required for update. 

**Expected behavior**
I should be able to use .update() on a model with attributes that are in the __casts__ list 

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Version Monterey 12.4

**What database are you using?**
 - Type: Postgres
 - Version 10.5
 - Masonite ORM 2.18.0

**Comment by BSN4** [comment]
related #755

**Comment by josephmancuso** [comment]
This presents a potential breaking change. I'll have to just verify

**Comment by josephmancuso** [comment]
Since this is a breaking change i put this in the 3.x branch. Release date should be around the beginning of september
