### ISSUE TITLE
Add additional schema indexes

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#76]
need to make sure we have: 

- [x] `primary`
- [x] `index`
- [x] `unique`
- [x] `fulltext `

We should have `primary` already

**Comment by josephmancuso** [comment]
Here is a good resource https://vanseodesign.com/web-design/create-add-indexes-mysql/

**Comment by corentinalcoy** [comment]
@josephmancuso assign to me

**Comment by josephmancuso** [comment]
I added `fulltext` to description

**Comment by corentinalcoy** [comment]
@josephmancuso  We have an issue.
With the base code there we can not do something like that
```MySQL

CREATE TABLE Customer(
   LastName CHAR(30) NOT NULL,
  FirstName CHAR(30) NOT NULL,
  Email CHAR(50) NOT NULL,
  INDEX (LastName,FirstName) 
);
```
or 
```MySQL

CREATE TABLE Customer(
   lastname varchar(30) not null,
  firstname varchar(30) not null,
  Email CHAR(50) not null,
  constraint email_lastname_unique UNIQUE (email, lastname) 
);
```

**Comment by corentinalcoy** [comment]
I think we should fix it before continue

**Comment by josephmancuso** [comment]
Hmm you are right. I'm gonna take another look at the schema stuff because the grammars for that are all broken down. They aren't well connected like the select query is.

Let me take a look at that tonight

**Comment by josephmancuso** [comment]
It seems to be difficult for you and @Marlysson to build these things out so thats a foundation problem

**Comment by corentinalcoy** [comment]
Okay
Keep in mind we can take the name of the index or constraint from like a parameter.

**Comment by josephmancuso** [comment]
yeah let me refactor some of the schema stuff first @Marlysson

**Comment by Marlysson** [comment]
@josephmancuso Do I keep the code intact while do you refactor this part, for while?

**Comment by josephmancuso** [comment]
yeah just keep everything the same. I will take a look tonight
