### ISSUE TITLE
get_related bug

### ISSUE THREAD

**Issue by mstfblci** [MasoniteFramework/orm#761]
**Describe the bug**
I use the has_many method in a model and if I want to get the data with the get related method, it gives all of them instead of giving the rows that are dependent on that model.

**Comment by josephmancuso** [comment]
It should not be `get_related()` you should be using `related()`

```python
User.find(1).related("phones").where(..).get()
```

**Comment by josephmancuso** [comment]
https://orm.masoniteproject.com/models#getting-the-relationship
