### ISSUE TITLE
BelongsTo relation has wrong amount of QueryBuilder arguments.

### ISSUE THREAD

**Issue by leannextang** [MasoniteFramework/orm#767]
This works at v2.17.2, but fails at v2.18.1.

**Steps to reproduce the behavior:**
1. Set module Contract:
```
class Contract(Model):
...
    @belongs_to
    def company(self):
        return models.Company
```
2.  Set module Company:
```
class Company(Model):
...
    @has_many('id', 'company_id')
    def contract(self):
        return models.Contract
 
    @scope
    def active(self, query):
        return query.where("status", 1)
```
3.  Call models.Contract.with_(('company' :models.Company.active()}).first().uid)

Error Message:
![image](https://user-images.githubusercontent.com/103096852/179655750-655368f8-f801-4f78-b1bf-2776d7701c4c.png)

**Desktop (please complete the following information):**
 - OS & FAQ : 
<img width="218" alt="image" src="https://user-images.githubusercontent.com/103096852/179660283-ff0c43f0-cb46-42ef-b113-e204cb054f73.png">

**Versions:**
 - Database: Postgres 12.11
 - Masonite ORM v2.18.1

**Comment by josephmancuso** [comment]
```python
models.Contract.with_({"company": models.Company.active()})
```

This is not the proper usage of this feature. You have to use a lambda expression that takes a query builder instance.

I believe you should be able to do something like:

```python
models.Contract.with_({"company": lambda q: q.active()})
```

**Comment by josephmancuso** [comment]
Please see docs here https://orm.masoniteproject.com/models#dynamic-relationships

**Comment by leannextang** [comment]
Thank you for the information,
we will check how to fix the legacy code here.
