### ISSUE TITLE
Hydration not working in `has_one` relationship

### ISSUE THREAD

**Issue by JRubics** [MasoniteFramework/orm#775]
When we have model with `has_one` relationship and want to access the related model fields, it is not hydrated, so it executes more queries than needed.

**Example**

Models:
```python
class Website(Model):
...
    @has_one('website_id', 'id')
    def database(self):
        from .database import Database
        return Database

```
When we try to access database fields this way:
```python
db_host=website.database.host
db_port=website.database.port
db_name=website.database.name
db_user=website.database.username
```
this query is executed for each accessing:
```SELECT * FROM `databases` WHERE `databases`.`website_id` = 1 LIMIT 1```

but when accessing database fields this way, query is executed only once:
```python
database = website.database
db_host=database.host
db_port=database.port
db_name=database.name
db_user=database.username
```

I was checking this by logging queries executed in mysql: https://asvignesh.in/mysql-log-all-queries-to-file-and-table/ 

**Desktop:**

    OS: Linux
    Version Ubuntu 21.10

**What database are you using?**

    Type: [MySQL]
    Version [14.14 Distrib 5.7.30, for Linux (x86_64) using EditLine wrapper]
    Masonite ORM [2.15.0]
    
**Aditional**

Can you please apply the patch to the version 2.15.0, because we tried to upgrade to 2.18.2 and it has some incompatibilities.

**Comment by josephmancuso** [comment]
that's the current correct behavior. We are not caching the database call once its called. It will work the way you want if you use a `with_("database")` when fetching your `Website`

**Comment by JRubics** [comment]
okay, thank you! :slightly_smiling_face:
