### ISSUE TITLE
FileNotFoundError *stub 

### ISSUE THREAD

**Issue by NawrasBukhari** [MasoniteFramework/orm#824]
**Describe the bug**

**To Reproduce**
1. integrate MasoniteOrm as a standalone script then run setup.py
2. Click on site_packages folder then search for the name and realize that stubs were not included
3. [error image](https://i.ibb.co/GHhZsQV/not-found-error.png)

**Expected behavior**
it's supposed to create a exe file where I can execute directly from terminal to access the CLI

fix here https://github.com/MasoniteFramework/orm/pull/823

**Comment by girardinsamuel** [comment]
Hi !
This PR is now closed, do you still experience this bug ? 🤔

**Comment by NawrasBukhari** [comment]
I have came up with a solution as I mentioned in the comments.
I have applied for a pull request and it will fix it for sure

**Comment by girardinsamuel** [comment]
Okay so can you can you reopen it so we can review it ? thanks !

**Comment by NawrasBukhari** [comment]
Reopened!
Please check. Thanks
