### ISSUE TITLE
`QueryBuilder.update()` does not respect model `__casts__`

### ISSUE THREAD

**Issue by zombeer** [MasoniteFramework/orm#831]
**Describe the feature as you'd like to see it**
In my code I rely on models casts for some fields. As far as I can see it's implemented everywhere in model methods, but querybuilder ones.
It would be really nice to have consistent behavior over all Model/QueryBuilder methods.
In order for change to be non breaking I suggest to add `cast=False` kwarg to `QueryBuilder.update()` to preserve current state of things by default.

**What do we currently have to do now?** 
To be exact:
I have to call `Model.update(..)` with some ugly `json.dumps(...)` inside while having `json` casts enabled in model.

- [ ] Is this a breaking change?

**Comment by zombeer** [comment]
PR attached (:
https://github.com/MasoniteFramework/orm/pull/832

**Comment by circulon** [comment]
Related to #759

**Comment by zombeer** [comment]
> Related to #759

Yep. But I suggest to implement non breaking change though.

**Comment by stoutput** [comment]
Also addressed in https://github.com/MasoniteFramework/orm/pull/830

**Comment by stoutput** [comment]
This has been fixed in #830

**Comment by josephmancuso** [comment]
closing then :)
