### ISSUE TITLE
Add complete type definitions

### ISSUE THREAD

**Issue by stoutput** [MasoniteFramework/orm#840]
**Describe the feature as you'd like to see it**
Clear, concise, and accurate type hints across the whole codebase, especially on the base model.

**What do we currently have to do now?** 
Incorrect and incomplete type hints, very little on the model (since most of its methods pass-through to QueryBuilder)

**Comment by josephmancuso** [comment]
we do i think? is there a specific method that doesnt show up?

<img width="566" alt="Screenshot 2023-09-30 at 1 07 36 PM" src="https://github.com/MasoniteFramework/orm/assets/20172538/d53d807e-d997-406b-93bf-157eb1c69599">
