### ISSUE TITLE
Ability to define custom computed properties on models

### ISSUE THREAD

**Issue by lekhnath** [MasoniteFramework/orm#844]
**Describe the feature as you'd like to see it**
Define computed property on Models

**What do we currently have to do now?** 

```python

class Product(Model):
    
    @property
     def amount_total(self):
        return self.rate * self.qty

```

**Additional context**
This is just an example but it would be nice if we could define custom properties on model and also select these
property dynamically using the select method. I've tried using **\_\_cast_map__** I could not manage to get the 
desired result. It is not selectable and the value returned from `get` method of `Caster` class also did not reflect in result.

**Demo implementation of \_\_cast_map__:**

```python
from masoniteorm.models import Model

class UsernameCaster:
    def get(self, value):
        return value.split('@')[0]

    def set(self, value):
        pass

class User(Model):
    __selects__ = ['id', 'email as username']
    __cast_map__ = {
        "username": UsernameCaster,
    }
```

- [ ] Is this a breaking change? **Not Sure**

**Comment by josephmancuso** [comment]
i think you're referring to mutators and accessors. if not ill reopen

https://orm.masoniteproject.com/models#accessors-and-mutators-getter-and-setter

**Comment by josephmancuso** [comment]
if you want to seect this you would have to use the add_select clause for the query builder. if you want the logic in the model you could use a scope and add it there
