### ISSUE TITLE
Little issue in first_or_create method

### ISSUE THREAD

**Issue by LordDeveloper** [MasoniteFramework/orm#848]
Code:
```python
user = User.first_or_create(
    {'id': sender_id}
)
```

Error:
`masoniteorm.query.QueryBuilder.QueryBuilder.create() got multiple values for keyword argument 'id_key'`

**Comment by cristianomg10** [comment]
Hi everybody. Unfortunately the same is happening for the **update_or_create** method.

**Comment by tpow** [comment]
This is the same problem as #843.

**Comment by josephmancuso** [comment]
Fixed in v2.19.2
