### ISSUE TITLE
Error trying to save Json in version 2.19.*

### ISSUE THREAD

**Issue by arturo-villalpando** [MasoniteFramework/orm#853]
**Describe the bug**

I used Fastapi + Masonite ORM + Strawberry

I'm trying to save a JSON in a JSON field of PostgreSQL, the problem is that when I trying im getting the next error:

Message:

masoniteorm.query.QueryBuilder.QueryBuilder.create() got multiple values for keyword argument 'id_key'

![Captura de pantalla 2023-07-13 a la(s) 18 09 24](https://github.com/MasoniteFramework/orm/assets/58632310/6d25569f-435d-415d-a5a6-126ba12a178f)

**To Reproduce**
1. Go to https://github.com/arturo-villalpando/FMS
2. Clone the repo and install the requirements

pip3 install -r requirements.txt

3. Run the repo and go to http://localhost:8000/graphql
4. Try to execute the next query for add a fat category:

`mutation MyMutation {
  addFaqCategory(
    data: {category: "[{\"category\":\"Basketball\"}]", deletedAt: null}
  ) {
    id
    category
    deletedAt
  }
}`

5.- Go to the requirements.txt file and change the version of masonite-orm to 2.19.*
6.- Run again the query an you will get the error

**Expected behavior**
Save the json in database:

![Captura de pantalla 2023-07-13 a la(s) 18 17 32](https://github.com/MasoniteFramework/orm/assets/58632310/d01f33bb-c1e6-41f4-b9ca-893c616bc272)

**Screenshots or code snippets**
Screenshots help a lot. If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Version: 13.4.1

**What database are you using?**
 - Type: Postgres
 - Version: 14.8
 - Masonite ORM: 2.19.*

**Additional context**
There is no problem trying to save the json in Masonite ORM version 2.18.6.

**Comment by josephmancuso** [comment]
this is fixed in v2.19.2
