### ISSUE TITLE
Postgres psycopg2 TLS connectivity 

### ISSUE THREAD

**Issue by nictrix** [MasoniteFramework/orm#875]
**Describe the feature as you'd like to see it**

I don't think connecting to a Postgres Database over TLS is currently possible based on what code I saw when connecting via psycopg2. I would like to use `sslmode, sslrootcert options and that doesn't appear to be possible. 

**What do we currently have to do now?** 

Please confirm if this is a valid feature to add, if so I can submit some code to enable this ability. I believe all we need to do is add on a general **kwargs parameter to the make_connection function and pass that along since psycopg2 can handle it. 

**Additional context**

Great project by the way! Really appreciate the work put into it!

- [ ] Is this a breaking change? No

**Comment by josephmancuso** [comment]
I agree with this. as long as we can pass it to the psycopg2 connection class we can make a configuration for it in the connection settings
