### ISSUE TITLE
Model queryBuilder should only select columns for that model

### ISSUE THREAD

**Issue by circulon** [MasoniteFramework/orm#902]
**Describe the bug**
By default the QueryBuilder attached to a model via `Model.builder.xxx 
uses `SELECT * FROM <model_table> ...` as the default select criteria.

This is an issue when adding join clauses (and possibly other clauses) either via scopes or as part of a models query.
This causes the Model to be loaded with every column returned by the query,

Additionally any column names from other tables that have the same name as the ones in the model (id is a prime example)
will be updated with the value from the other tables column creating a model that is not the same as the row in the DB. 

**To Reproduce**
Assume the following models:
```python
class Company(Model):
    id: int
    name: str
    email: string

class User(Model):
    id: int
    company_id: int
    first_name: string
    last_name: string
    email: string

    @scope
    def with_email(self, query, email):
        c_table = Company.get_table_name()
        company_join = (
            JoinClause(f"{c_table} as ct")
            .on("company_id", "=", "ct.id")
            .on_value("user.email", "=", email)
        ) 
        return query.join(company_join)
```
assume the following tables and rows:

Table: company
| id | name | email |
| ---- | ---------- | -------------------- |
| 1 | Acme | support@acme.com |
| 2 | Ego | admin@ego.net |
| 3 | Tools R Us | info@toolsrus.org |

Table: user
| id | company_id | first_name | last_name | email |
| ---- | ---- | ---------- | ---------- | -------------------- |
| 1 | 2 | Bob | Down | bob@ego.net |
| 2 | 2 | James | Brown | james@ego.net |
| 3 | 1 | Steve | Jones | steve@acme.com |
| 4 | 3 | Mark | Black | mark@toolsrus.org |
| 5 | 3 | James | Jameson | james@toolsrus.org |

query to find "James" from "Tools R Us"
```python
query = User.with_email("james@toolsrus.org")
print(query.to_sql())
user = query.first()
print(user.serialize())
```
Generated query will be similar to:
```sql
SELECT * FROM "user" INNER JOIN "company" AS "ct" ON "user"."company_id" = "ct"."id" AND "user"."email" = 'james@toolsrus.org'
```
Row data returned looks similar to this:
| id | company_id | first_name | last_name | email | id | name | email |
| ---- | ---- | ---------- | ---------- | -------------------- | ---- | ---------- | -------------------- |
| 5 | 3 | James | Jameson | james@toolsrus.org | 3 | Tools R Us | info@toolsrus.org |

Serialized user will be similar to 
```python
{'id': 3, 'company_id': 3, 'first_name': 'James', 'last_name': 'Jameson', 'email': 'info@toolsrus.org', 'name': 'Tools R Us'}
```
Notice: 
- the 'id' is 3 which is the company_id not 5 as expected
- the 'email' is the email address of the company not the user as expected.
- the additional field 'name' which is not one of the columns in the 'user' table and containing the name of the company 

**Expected behavior**
Generated query would be similar to:
```sql
SELECT "user".* FROM "user" INNER JOIN "company" AS "ct" ON "user"."company_id" = "ct"."id" AND "user"."email" = 'james@toolsrus.org'
```
Serialized user model would contain only columns relevant to the 'user' table 
```python
{'id': 5, 'company_id': 3, 'first_name': 'James', 'last_name': 'Jameson', 'email': 'james@toolsrus.org'}
```

**Screenshots or code snippets**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Version 12.7

**What database are you using?**
 - Type: Postgres,  SQLite3
 - Version 14
 - Masonite ORM 2.23.1

**Additional context**
The general fix for this would look to be fairly simple:
when the QueryBuilder is created via a `Model.builer` call if there is no explicit .select() then the select that gets added would be something like this
```python
self.select = f"SELECT {self.model.get_table_name()}.* "
```
This would then by defacult only get the columns that are used in the model.

**Comment by josephmancuso** [comment]
if youre doing a complex join like this with ambiguous fields you can do a select on the model.

```
query = User.select("users.*, users.id as user_id, ct.id as ct_id").with_email("james@toolsrus.org")
```

**Comment by circulon** [comment]
@josephmancuso 
> if youre doing a complex join like this with ambiguous fields you can do a select on the model.
> 
> ```
> query = User.select("users.*, users.id as user_id, ct.id as ct_id").with_email("james@toolsrus.org")
> ```
Yes you are quite correct and it can be done that way.
Notice that you specified `users.*` in the select which limits the initial columns selected (along with a couple of other specific ones)
This highlights my point exactly in that if no `select` criteria is provided when selecting columns to hydrate a model with then the default should be to ONLY select the columns that are for the Model itself. 
A join clause in the default Model hydration context is generally used as more specific criteria for finding the data to hydrate the model with.

Looking at the issue description I should have put this next example in the description above... sorry ;(
So in my example above  to use the scope correctly in the default context you have to do this
```python
query = User.select("user.*").with_email("james@toolsrus.org")
```
Which is not intuitive or even obvious and is not noted in the Model documentation.
ie when building criteria for Model to be hydrated with, you MUST use a `.select()` which limits the columns returned to only the ones required for the Model when the query could return columns from multiple tables that may have the same name.

I have a PR coming which will hilight and test this default scenario

I hope this clarifies what I am trying to hilight.

Happy to dicuss further ;)

**Comment by josephmancuso** [comment]
i lean more towards not accepting this.

Another option if you need to do this at a more global level is putting a global select on your model:

```python
class User(Model):

    __selects__ = ["users.*"]
```

then you can do this and the `users.*` will automatically be added to the select statement without specifying it

```python
User.with_email("james@toolsrus.org")
# select users.*, ... from users ...
```

**Comment by josephmancuso** [comment]
what i can also suggest is we create a getter inside the base Model class.

so on line 357 of src/masoniteorm/models/Model.py

we have this line:

```python
        return self.builder.select(*self.__selects__)
```

if we changed it to:

```python
        return self.builder.select(*self.get_selects())
```

with a getter like 

```python
def get_selects(self):
    return self.__selects__
```

what this will allow you do is is create a base model to override the getter:

```python
class BaseModel(Model):

    def get_selects(self):
        return [self.get_table_name()+".*"]
```

```python
class User(BaseModel):
    pass
```

i think it should just work like that for every model without doing anything else.

**Comment by circulon** [comment]
@josephmancuso 
> what this will allow you do is is create a base model to override the getter:
> 
> ```python
> class BaseModel(Model):
> 
>     def get_selects(self):
>         return [self.get_table_name()+".*"]
> ```
> 
> ```python
> class User(BaseModel):
>     pass
> ```
> 
> i think it should just work like that for every model without doing anything else.

I didnt notice the Model has a `__selects__`  attribute,  I was only considering the parameters loaded into the QueryBuilder just before making the connection to the DB.  
I also  see how this would work more globally and using a BaseModel (which I personally always do anyway ;) 
is a good practice.

It also removes the need to handle cases like this from the QueryBuilder itself which is good too ;)

We will need to add some additional explanation/notes in the Model docs to advise devs this would be a recommended usage pattern if they use joins in a Model scopes or if they use joins for criteria when hydrating models in general.

I will put together a PR based on what you described along with some tests.  

Thanks for the discssion, your deeper understanding has been very insightful
